Team 7UP Jordan                 = #1b6d3e
Mild Seven Benetton Renault     = #4a9ecd
Scuderia Ferrari                = #dc0000
Mercedes AMG Petronas F1 Team   = #00d2be
Vodafone McLaren Mercedes       = #FF9800
Alfa Romeo SpA                  = #900000
Officine Alfieri Maserati       = #d40000
Novi Auto Air Conditioner       = #848b92
Renault F1 Team                 = #fff500
Williams Racing                 = #005aff
Sauber F1 Team                  = #9b0000
Scuderia Toro Rosso             = #000084
Red Bull Racing                 = #0600ef
Aston Martin Cognizant F1 Team  = #006f62
Cooper Car Company              = #002215
Rob Walker Racing Team          = #7c7f80
Motor Racing Developments, Ltd. = #01639d
Owen Racing Organisation        = #182622
Matra International             = #1d6fb8
Elf Team Tyrrell                = #063f87
STP March Racing Team           = #fef047
Marlboro-BRM                    = #c0c7bf
Parmalat Racing Team            = #282934
Team Tissot Ensign              = #dd2125
BS Fabrications                 = #e9ebed
Team Lotus                      = #ffb800
Toleman Group Motorsport        = #2c355e
Scuderia Lancia                 = #fe2932
Embassy Racing with Graham Hill = #d7e3e0
Fittipaldi Automotive           = #fdf517
European Minardi F1             = #010203
Alpine F1 Team                  = #0090ff
Vandervell Products             = #00503f
Porsche System Engineering      = #949896
Automobili Turismo e Sport      = #de7a8c
Anglo American Racers           = #24263e
Honda Racing                    = #ece7e3
Team Surtees                    = #182550
Olympus Cameras Wolf Racing     = #e7c4ab
Vel's Parnelli Jones Racing     = #c4002e
Shadow Racing Team              = #3e6fc5
Arrows Racing Team              = #ba4f63
Team Haas                       = #e05c45
Theodore Racing Hong Kong       = #57513e
ATS Racing Team                 = #e4a50c
Brawn GP F1 Team                = #f2f279
Scuderia AlphaTauri             = #2b4562
Ligier Lotos                    = #0046cc