<?php
    declare(strict_types=1);// modo estrito
    $drivers = [
        [
            'name' => 'Max Verstappen',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/max-verstappen.html',
            'team' => 'Red Bull Racing Honda',
            'number' => 33,
            'birthYear' => 1997,
            'nationality' => 'Netherlands',
            'world_championships' => 0,
            'wins' => 19,
            'first_win' => 'Formula 1 Gran Premio de España Pirelli 2016',
            'last_win' => 'Formula 1 Gran Premio de la Ciudad de México 2021',
            'podiums' => 58,
            'points' => 1513.5,
            'grands_prix' => 139,
            'first_race' => '2015 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 12,
            'fastest_laps' => 15,
            'highest_race_finish' => '1 (19x)',
            'last_team' => 'Red Bull Toro Rosso Honda (Scuderia Toro Rosso)',
        ],
        [
            'name' => 'Lewis Hamilton',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/lewis-hamilton.html',
            'team' => 'Mercedes-AMG Petronas F1 Team',
            'number' => 44,
            'birthYear' => 1985,
            'nationality' => 'Great Britain',
            'world_championships' => '7 (2008, 2014, 2015, 2017, 2018, 2019, 2020)',
            'wins' => 102,
            'first_win' => 'Formula 1 Grand Prix du Canada 2007',
            'last_win' => 'Formula 1 Ooredoo Qatar Grand Prix 2021',
            'podiums' => 180,
            'points' => 4121.5,
            'grands_prix' => 286,
            'first_race' => '2007 Formula 1 ING Australian Grand Prix',
            'pole_positions' => 102,
            'fastest_laps' => 58,
            'highest_race_finish' => '1 (102x)',
            'last_team' => 'McLaren F1 Team (Vodafone McLaren Mercedes)',
        ],
        [
            'name' => 'Valtteri Bottas',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/valtteri-bottas.html',
            'team' => 'Mercedes-AMG Petronas F1 Team',
            'number' => 77,
            'birthYear' => 1989,
            'nationality' => 'Finland',
            'world_championships' => 0,
            'wins' => 10,
            'first_win' => '2017 Formula 1 VTB Russian Grand Prix',
            'last_win' => 'Formula 1 Rolex Turkish Grand Prix 2021',
            'podiums' => 66,
            'points' => 1715,
            'grands_prix' => 176,
            'first_race' => '2013 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 20,
            'fastest_laps' => 19,
            'highest_race_finish' => '1 (10x)',
            'last_team' => 'Williams Racing (Williams Martini Racing)',
        ],
        [
            'name' => 'Sergio Perez',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/sergio-perez.html',
            'team' => 'Red Bull Racing Honda',
            'number' => 11,
            'birthYear' => 1990,
            'nationality' => 'Mexico',
            'world_championships' => 0,
            'wins' => 2,
            'first_win' => 'Formula 1 Rolex Sakhir Grand Prix 2020',
            'last_win' => 'Formula 1 Azerbaijan Grand Prix 2021',
            'podiums' => 15,
            'points' => 896,
            'grands_prix' => 212,
            'first_race' => '2011 Formula 1 Qantas Australian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 6,
            'highest_race_finish' => '1 (2x)',
            'last_team' => 'BWT Racing Point F1 Team (BWT Racing Point F1 Team)',
        ],
        [
            'name' => 'Lando Norris',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/lando-norris.html',
            'team' => 'McLaren F1 Team',
            'number' => 4,
            'birthYear' => 1999,
            'nationality' => 'Great Britain',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 5,
            'points' => 299,
            'grands_prix' => 58,
            'first_race' => 'Formula 1 Rolex Australian Grand Prix 2019',
            'pole_positions' => 1,
            'fastest_laps' => 3,
            'highest_race_finish' => '2 (1x)',
            'last_team' => 'Carlin (FIA Formula 2 Championship)',
        ],
        [
            'name' => 'Charles Leclerc',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/charles-leclerc.html',
            'team' => 'Scuderia Ferrari Mission Winnow',
            'number' => 16,
            'birthYear' => 1997,
            'nationality' => 'Monaco',
            'world_championships' => 0,
            'wins' => 2,
            'first_win' => 'Formula 1 Johnnie Walker Belgian Grand Prix 2019',
            'last_win' => 'Formula 1 Gran Premio Heineken d Italia 2019',
            'podiums' => 13,
            'points' => 553,
            'grands_prix' => 79,
            'first_race' => 'Formula 1 2018 Rolex Australian Grand Prix',
            'pole_positions' => 9,
            'fastest_laps' => 4,
            'highest_race_finish' => '1 (9x)',
            'last_team' => 'Alfa Romeo Racing Orlen (Alfa Romeo Sauber F1 Team)',
        ],
        [
            'name' => 'Carlos Sainz',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/carlos-sainz.html',
            'team' => 'Scuderia Ferrari Mission Winnow',
            'number' => 55,
            'birthYear' => 1994,
            'nationality' => 'Spain',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 5,
            'points' => 517.5,
            'grands_prix' => 139,
            'first_race' => '2015 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 1,
            'highest_race_finish' => '2 (2x)',
            'last_team' => 'McLaren F1 Team (McLaren F1 Team)',
        ],
        [
            'name' => 'Daniel Ricciardo',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/daniel-ricciardo.html',
            'team' => 'McLaren F1 Team',
            'number' => 3,
            'birthYear' => 1989,
            'nationality' => 'Australia',
            'world_championships' => 0,
            'wins' => 8,
            'first_win' => 'Formula 1 Grand Prix du Canada 2014',
            'last_win' => 'Formula 1 Heineken Gran Premio d Italia 2021',
            'podiums' => 32,
            'points' => 896,
            'grands_prix' => 208,
            'first_race' => '2011 Formula 1 Santander British Grand Prix',
            'pole_positions' => 3,
            'fastest_laps' => 16,
            'highest_race_finish' => '1 (8x)',
            'last_team' => 'Renault F1 Team (Renault DP World F1 Team)',
        ],
        [
            'name' => 'Pierre Gasly',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/pierre-gasly.html',
            'team' => 'Scuderia AlphaTauri Honda',
            'number' => 10,
            'birthYear' => 1996,
            'nationality' => 'France',
            'world_championships' => 0,
            'wins' => 1,
            'first_win' => 'Formula 1 Gran Premio Heineken d Italia 2020',
            'last_win' => 'Formula 1 Gran Premio Heineken d Italia 2020',
            'podiums' => 3,
            'points' => 291,
            'grands_prix' => 84,
            'first_race' => '2017 Formula 1 Petronas Malaysia Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 3,
            'highest_race_finish' => '1 (1x)',
            'last_team' => 'Red Bull Toro Rosso Honda (Red Bull Toro Rosso Honda)',
        ],
        [
            'name' => 'Fernando Alonso',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/fernando-alonso.html',
            'team' => 'Alpine F1 Team',
            'number' => 14,
            'birthYear' => 1981,
            'nationality' => 'Spain',
            'world_championships' => '2 (2005, 2006)',
            'wins' => 32,
            'first_win' => 'Marlboro Magyar Nagydíj 2003',
            'last_win' => 'Formula 1 Gran Premio de España 2013',
            'podiums' => 98,
            'points' => 1976,
            'grands_prix' => 334,
            'first_race' => 'LXVI Qantas Australian Grand Prix 2001',
            'pole_positions' => 22,
            'fastest_laps' => 23,
            'highest_race_finish' => '1 (32x)',
            'last_team' => 'Arrow McLaren SP (IndyCar Series)',
        ],
        [
            'name' => 'Esteban Ocon',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/fernando-alonso.html',
            'team' => 'Alpine F1 Team',
            'number' => 31,
            'birthYear' => 1996,
            'nationality' => 'France',
            'world_championships' => 0,
            'wins' => 1,
            'first_win' => 'Formula 1 Rolex Magyar Nagydíj 2021',
            'last_win' => 'Formula 1 Rolex Magyar Nagydíj 2021',
            'podiums' => 2,
            'points' => 258,
            'grands_prix' => 87,
            'first_race' => '2016 Formula 1 Belgian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '1 (1x)',
            'last_team' => 'Renault F1 Team (Renault DP World F1 Team)',
        ],
        [
            'name' => 'Sebastian Vettel',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/S/SEBVET01_Sebastian_Vettel/sebvet01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/sebastian-vettel.html',
            'team' => 'Aston Martin Cognizant F1 Team',
            'number' => 5,
            'birthYear' => 1987,
            'nationality' => 'Germany',
            'world_championships' => '4 (2010, 2011, 2012, 2013)',
            'wins' => 53,
            'first_win' => 'Formula 1 Gran Premio Santander D Italia 2008',
            'last_win' => 'Formula 1 Singapore Airlines Singapore Grand Prix 2019',
            'podiums' => 122,
            'points' => 3061,
            'grands_prix' => 278,
            'first_race' => '2007 Formula 1 United States Grand Prix',
            'pole_positions' => 57,
            'fastest_laps' => 38,
            'highest_race_finish' => '1 (53x)',
            'last_team' => 'Scuderia Ferrari Mission Winnow (Scuderia Ferrari)',
        ],
        [
            'name' => 'Lance Stroll',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/lance-stroll.html',
            'team' => 'Aston Martin Cognizant F1 Team',
            'number' => 5,
            'birthYear' => 1998,
            'nationality' => 'Canada',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 3,
            'points' => 176,
            'grands_prix' => 98,
            'first_race' => '2017 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 1,
            'fastest_laps' => 0,
            'highest_race_finish' => '3 (3x)',
            'last_team' => 'BWT Racing Point F1 Team (BWT Racing Point F1 Team)',
        ],
        [
            'name' => 'Yuki Tsunoda',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/yuki-tsunoda.html',
            'team' => 'Scuderia AlphaTauri Honda',
            'number' => 22,
            'birthYear' => 2000,
            'nationality' => 'Japan',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 20,
            'grands_prix' => 20,
            'first_race' => 'Formula 1 Gulf Air Bahrain Grand Prix 2021',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '6 (1x)',
            'last_team' => 'Carlin (FIA Formula 2 Championship)',
        ],
        [
            'name' => 'George Russel',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/george-russell.html',
            'team' => 'Williams Racing',
            'number' => 63,
            'birthYear' => 1998,
            'nationality' => 'Great Britain',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 1,
            'points' => 19,
            'grands_prix' => 58,
            'first_race' => 'Formula 1 Rolex Australian Grand Prix 2019',
            'pole_positions' => 0,
            'fastest_laps' => 1,
            'highest_race_finish' => '2 (1x)',
            'last_team' => 'Mercedes-AMG Petronas F1 Team (Mercedes-AMG Petronas F1 Team)',
        ],
        [
            'name' => 'Kimi Räikkönen',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/K/KIMRAI01_Kimi_R%C3%A4ikk%C3%B6nen/kimrai01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/kimi-raikkonen.html',
            'team' => 'Alfa Romeo Racing ORLEN',
            'number' => 7,
            'birthYear' => 1979,
            'nationality' => 'Finland',
            'world_championships' => '1 (2007)',
            'wins' => 21,
            'first_win' => '2003 Petronas Malaysian Grand Prix',
            'last_win' => 'Formula 1 Pirelli 2018 United States Grand Prix',
            'podiums' => 103,
            'points' => 1873,
            'grands_prix' => 350,
            'first_race' => 'LXVI Qantas Australian Grand Prix 2001',
            'pole_positions' => 18,
            'fastest_laps' => 46,
            'highest_race_finish' => '1 (21x)',
            'last_team' => 'Scuderia Ferrari Mission Winnow (Scuderia Ferrari)',
        ],
        [
            'name' => 'Nicholas Latifi',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/N/NICLAF01_Nicholas_Latifi/niclaf01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/nicholas-latifi.html',
            'team' => 'Williams Racing',
            'number' => 6,
            'birthYear' => 1995,
            'nationality' => 'Canada',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 7,
            'grands_prix' => 37,
            'first_race' => 'Formula 1 Rolex Großer Preis von Österreich 2020',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '7 (1x)',
            'last_team' => 'DAMS (FIA Formula 2 Championship)',
        ],
        [
            'name' => 'Antonio Giovinazzi',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/A/ANTGIO01_Antonio_Giovinazzi/antgio01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/antonio-giovinazzi.html',
            'team' => 'Alfa Romeo Racing ORLEN',
            'number' => 9,
            'birthYear' => 1993,
            'nationality' => 'Italy',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 19,
            'grands_prix' => 60,
            'first_race' => '2017 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '5 (1x)',
            'last_team' => 'AF Corse (24 Hours of Le Mans – LMGTE Pro)',
        ],
        [
            'name' => 'Mick Schumacher',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/M/MICSCH02_Mick_Schumacher/micsch02.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/mick-schumacher.html',
            'team' => 'Uralkali Haas F1 Team',
            'number' => 47,
            'birthYear' => 1999,
            'nationality' => 'Switzerland',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 0,
            'grands_prix' => 20,
            'first_race' => 'Formula 1 Gulf Air Bahrain Grand Prix 2021',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '12 (1x)',
            'last_team' => 'Prema Racing (Formula 2 Championship)',
        ],
        [
            'name' => 'Robert Kubica',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/R/ROBKUB01_Robert_Kubica/robkub01.png.transform/2col/image.png',
            'website' => 'https://www.formula1.com/en/drivers/robert-kubica.html',
            'team' => 'Alfa Romeo Racing ORLEN',
            'number' => 88,
            'birthYear' => 1984,
            'nationality' => 'Polish',
            'world_championships' => 0,
            'wins' => 1,
            'first_win' => 'Formula 1 Grand Prix du Canada 2008',
            'last_win' => 'Formula 1 Grand Prix du Canada 2008',
            'podiums' => 12,
            'points' => 274,
            'grands_prix' => 99,
            'first_race' => 'Formula 1 Magyar Nagydíj 2006',
            'pole_positions' => 1,
            'fastest_laps' => 1,
            'highest_race_finish' => '1 (1x)',
            'last_team' => 'High Class Racing (FIA World Endurance Championship - LMP2)',
        ],
        [
            'name' => 'Nikita Mazepin',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/N/NIKMAZ01_Nikita_Mazepin/nikmaz01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/nikita-mazepin.html',
            'team' => 'Uralkali Haas F1 Team',
            'number' => 9,
            'birthYear' => 1999,
            'nationality' => 'Russia',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 0,
            'grands_prix' => 20,
            'first_race' => 'Formula 1 Gulf Air Bahrain Grand Prix 2021',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '14 (1x)',
            'last_team' => 'Hitech Grand Prix (FIA Formula 2 Championship)',
        ],
    ];
    $teams = [
        [
            'name' => 'Mercedes-AMG Petronas F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Mercedes/_jcr_content/logo.img.jpg/1582638425211.jpg',
            'website' => 'https://www.formula1.com/en/teams/Mercedes.html',
            'year' => 1954,
            'championships' => '7 (2014, 2015, 2016, 2017, 2018, 2019, 2020)',
            'driversChampionships' => '9 (1954, 1955, 2014, 2015, 2016, 2017, 2018, 2019, 2020)',
            'wins' => 114,
            'podiums' => 261,
            'pole_positions' => 126,
            'fastest_laps' => 84,
            'base' => 'Brackley, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Mercedes-AMG F1 W12 E Performance',
            'racesEntered' => 247,
            'firstEntry' => '1954 French Grand Prix',
            'lastWin' => 'Formula 1 Ooredoo Qatar Grand Prix 2021',
            'firstWin' => '1954 French Grand Prix',
            'highestraceResult' => '1 (114x)',
            'teamPrincipal' => 'Toto Wolff',
            'technical_chief' => 'Mike Elliott',
        ],
        [
            'name' => 'Red Bull Racing Honda',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Red-Bull-Racing/_jcr_content/logo.img.jpg/1610719164360.jpg',
            'website' => 'https://www.formula1.com/en/teams/Red-Bull-Racing.html',
            'year' => 1997,
            'championships' => '4 (2010, 2011, 2012, 2013)',
            'driversChampionships' => '4 (2010, 2011, 2012, 2013)',
            'wins' => 74,
            'podiums' => 204,
            'pole_positions' => 72,
            'fastest_laps' => 75,
            'base' => 'Milton Keynes, United Kingdom',
            'powerUnit' => 'Honda',
            'engine' => 'Honda RA621H',
            'chassis' => 'Red Bull Racing RB16',
            'racesEntered' => 324,
            'firstEntry' => '1997 Australian Grand Prix',
            'lastWin' => 'Formula 1 Gran Premio de la Ciudad de México 2021',
            'firstWin' => '2009 Formula 1 Chinese Grand Prix',
            'highestraceResult' => '1 (74x)',
            'teamPrincipal' => 'Christian Horner',
            'technical_chief' => 'Pierre Waché',
        ],
        [
            'name' => 'Scuderia Ferrari Mission Winnow',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Ferrari/_jcr_content/logo.img.jpg/1521797474166.jpg',
            'website' => 'https://www.formula1.com/en/teams/Ferrari.html',
            'year' => 1950,
            'championships' => '16 (1961, 1964, 1975, 1976, 1977, 1979, 1982, 1983, 1999, 2000, 2001, 2002, 2003, 2004, 2007, 2008)',
            'driversChampionships' => '15 (1952, 1953, 1956, 1958, 1961, 1964, 1975, 1977, 1979, 2000, 2001, 2002, 2003, 2004, 2007)',
            'wins' => 239,
            'podiums' => 772,
            'pole_positions' => 223,
            'fastest_laps' => 253,
            'base' => 'Maranello, Italy',
            'powerUnit' => 'Ferrari',
            'engine' => 'Ferrari 065/6',
            'chassis' => 'Ferrari SF21',
            'racesEntered' => 1030,
            'firstEntry' => 'Prix de Monte-Carlo et XIe Grand Prix Automobile',
            'lastWin' => 'Formula 1 Singapore Airlines Singapore Grand Prix 2019',
            'firstWin' => '1951 British Grand Prix',
            'highestraceResult' => '1 (239x)',
            'teamPrincipal' => 'Mattia Binotto',
            'technical_chief' => 'Enrico Cardile & Enrico Gualtieri',
        ],
        [
            'name' => 'McLaren F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/McLaren/_jcr_content/logo.img.jpg/1515152760829.jpg',
            'website' => 'https://www.formula1.com/en/teams/McLaren.html',
            'year' => 1966,
            'championships' => '8 (1974, 1984, 1985, 1988, 1989, 1990, 1991, 1998)',
            'driversChampionships' => '12 (1974, 1976, 1984, 1985, 1986, 1988, 1989, 1990, 1991, 1998, 1999, 2008)',
            'wins' => 183,
            'podiums' => 493,
            'pole_positions' => 156,
            'fastest_laps' => 160,
            'base' => 'Woking, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes-AMG F1 M12 E Performance',
            'chassis' => 'McLaren MCL35',
            'racesEntered' => 904,
            'firstEntry' => '1966 Monaco Grand Prix',
            'lastWin' => 'Formula 1 Heineken Gran Premio d Italia 2021',
            'firstWin' => '1968 Belgian Grand Prix',
            'highestraceResult' => '1 (183x)',
            'teamPrincipal' => 'Andreas Seidl',
            'technical_chief' => 'James Key',
        ],
        [
            'name' => 'Alpine F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Alpine/_jcr_content/logo.img.jpg/1611246834255.jpg',
            'website' => 'https://www.formula1.com/en/teams/Alpine.html',
            'year' => 1986,
            'championships' => '2 (2005, 2006)',
            'driversChampionships' => '2 (2005, 2006)',
            'wins' => 21,
            'podiums' => 232,
            'pole_positions' => 20,
            'fastest_laps' => 15,
            'base' => 'Enstone, United Kingdom',
            'powerUnit' => 'Renault',
            'engine' => 'Renault E-Tech 20B',
            'chassis' => 'Alpine A521',
            'racesEntered' => 760,
            'firstEntry' => '1986 Brazilian Grand Prix',
            'lastWin' => 'Formula 1 Rolex Magyar Nagydíj 2021',
            'firstWin' => 'XV Fuji Television Japanese Grand Prix 1989',
            'highestraceResult' => '1 (21x)',
            'teamPrincipal' => 'Davide Brivio',
            'technical_chief' => 'Pat Fry & Remi Taffin',
        ],
        [
            'name' => 'Scuderia AlphaTauri Honda',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/AlphaTauri/_jcr_content/logo.img.jpg/1582650557134.jpg',
            'website' => 'https://www.formula1.com/en/teams/AlphaTauri.html',
            'year' => 1985,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 2,
            'podiums' => 5,
            'pole_positions' => 1,
            'fastest_laps' => 2,
            'base' => 'Faenza, Italy',
            'powerUnit' => 'Honda',
            'engine' => 'Honda RA621H',
            'chassis' => 'AlphaTauri AT02',
            'racesEntered' => 651,
            'firstEntry' => 'XIV Grande Prêmio do Brasil 1985',
            'lastWin' => 'Formula 1 Gran Premio Heineken d Italia 2020',
            'firstWin' => 'Formula 1 Gran Premio Santander D Italia 2008',
            'highestraceResult' => '1 (2x)',
            'teamPrincipal' => 'Franz Tost',
            'technical_chief' => 'Jody Egginton',
        ],
        [
            'name' => 'Aston Martin Cognizant F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Aston-Martin/_jcr_content/logo.img.png/1610642928926.png',
            'website' => 'https://www.formula1.com/en/teams/Aston-Martin.html',
            'year' => 2018,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 1,
            'podiums' => 1,
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'base' => 'Silverstone, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Aston Martin AMR21',
            'racesEntered' => 73,
            'firstEntry' => 'Formula 1 2018 Johnnie Walker Belgian Grand Prix',
            'lastWin' => 'Formula 1 Rolex Sakhir Grand Prix 2020',
            'firstWin' => 'Formula 1 Rolex Sakhir Grand Prix 2020',
            'highestraceResult' => '1 (1x)',
            'teamPrincipal' => 'Otmar Szafnauer',
            'technical_chief' => 'Andrew Green',
        ],
        [
            'name' => 'Williams Racing',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Williams/_jcr_content/logo.img.jpg/1590743731407.jpg',
            'website' => 'https://www.formula1.com/en/teams/Williams.html',
            'year' => 1978,
            'championships' => '9 (1980, 1981, 1986, 1987, 1992, 1993, 1994, 1996, 1997)',
            'driversChampionships' => '7 (1980, 1982, 1987, 1992, 1993, 1996, 1997)',
            'wins' => 114,
            'podiums' => 313,
            'pole_positions' => 129,
            'fastest_laps' => 133,
            'base' => 'Grove, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Williams FW43',
            'racesEntered' => 768,
            'firstEntry' => '1978 Argentine Grand Prix',
            'lastWin' => 'Formula 1 Gran Premio de España Santander 2012',
            'firstWin' => 'XXXII Marlboro British Grand Prix 1979',
            'highestraceResult' => '1 (114x)',
            'teamPrincipal' => 'Jost Capito',
            'technical_chief' => 'François-Xavier Demaison',
        ],
        [
            'name' => 'Alfa Romeo Racing ORLEN',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Alfa-Romeo-Racing/_jcr_content/logo.img.jpg/1582650603836.jpg',
            'website' => 'https://www.formula1.com/en/teams/Alfa-Romeo-Racing.html',
            'year' => 1993,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 1,
            'podiums' => 27,
            'pole_positions' => 1,
            'fastest_laps' => 5,
            'base' => 'Hinwil, Switzerland',
            'powerUnit' => 'Ferrari',
            'engine' => 'Ferrari 065/6',
            'chassis' => 'Alfa Romeo Racing C41',
            'racesEntered' => 523,
            'firstEntry' => '1993 South African Grand Prix',
            'lastWin' => 'Formula 1 Grand Prix du Canada 2007',
            'firstWin' => 'Formula 1 Grand Prix du Canada 2007',
            'highestraceResult' => '1 (1x)',
            'teamPrincipal' => 'Frédéric Vasseur',
            'technical_chief' => 'Jan Monchaux',
        ],
        [
            'name' => 'Uralkali Haas F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Haas-F1-Team/_jcr_content/logo.img.jpg/1615481143675.jpg',
            'website' => 'https://www.formula1.com/en/teams/Haas-F1-Team.html',
            'year' => 2016,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 0,
            'podiums' => 0,
            'pole_positions' => 0,
            'fastest_laps' => 2,
            'base' => 'Kannapolis, United States',
            'powerUnit' => 'Ferrari',
            'engine' => 'Ferrari 065/6',
            'chassis' => 'Haas VF-21',
            'racesEntered' => 120,
            'firstEntry' => '2016 Formula 1 Rolex Australian Grand Prix',
            'lastWin' => '',
            'firstWin' => '',
            'highestraceResult' => '4 (1x)',
            'teamPrincipal' => 'Guenther Steiner',
            'technical_chief' => 'Simone Resta',
        ],
    ];
    $champions = [
        [
            'name' => 'Michael Schumacher',
            'image' => '../images/ms.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Michael_Schumacher.html',
            'activeYears' => '1991-2006, 2010-2012',
            'birthYear' => 1969,
            'nationality' => 'Germany',
            'world_championships' => '7 (1994, 1995, 2000, 2001, 2002, 2003, 2004)',
            'wins' => 91,
            'first_win' => '1992 Belgian Grand Prix (Camel Benetton Ford)',
            'last_win' => '2006 Formula 1 Sinopec Chinese Grand Prix (Scuderia Ferrari Marlboro)',
            'podiums' => 155,
            'grands_prix' => 308,
            'first_race' => '1991 Belgian Grand Prix (Team 7UP Jordan)',
            'lastRace' => 'Formula 1 Grande Prêmio Petrobras do Brasil 2012 (Mercedes AMG Petronas F1 Team)',
            'pole_positions' => 68,
            'fastest_laps' => 77,
            'highest_race_finish' => '1 (91x)',
            'otherTeams' => '<i style="color: #009994";>Mercedes AMG Petronas F1 Team</i> (2010-2012), <i style="color: #ed1c24";>Scuderia Ferrari Marlboro</i> (1996-2006), Mild Seven Benetton Renault (1991-1995), Team 7UP Jordan (1991)',
        ],
    ];
    $teamsWithWinsThisSeason = [
        'Mercedes-AMG Petronas F1 Team',
        'Red Bull Racing Honda',
        'McLaren F1 Team',
        'Alpine F1 Team'
    ];
    $races = [
        ['location' => 'Bahrein', 'date' => '1647745200', 'dateTime' => '2022-03-20 00:00:00', 'circuit' => 'Bahrain International Circuit', 'grand_prix' => 'Formula 1 Gulf Air Bahrain Grand Prix 2022'],
        ['location' => 'Arábia Saudita', 'date' => '1648350000', 'dateTime' => '2022-03-27 00:00:00', 'circuit' => 'Jeddah Corniche Circuit'],
        ['location' => 'Austrália', 'date' => '1649559600', 'dateTime' => '2022-04-10 00:00:00', 'circuit' => 'Albert Park Circuit'],
        ['location' => 'Itália', 'date' => '1649559600', 'dateTime' => '2022-04-10 00:00:00', 'circuit' => 'Albert Park Circuit'],
    ];