<?php
    declare(strict_types=1);// modo estrito
    $drivers = [
        [
            'name' => 'Max Verstappen',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/max-verstappen.html',
            'team' => 'Red Bull Racing Honda',
            'number' => 33,
            'birthYear' => 1997,
            'nationality' => 'Netherlands',
            'world_championships' => 0,
            'wins' => 19,
            'first_win' => 'Formula 1 Gran Premio de España Pirelli 2016',
            'last_win' => 'Formula 1 Gran Premio de la Ciudad de México 2021',
            'podiums' => 58,
            'points' => 1513.5,
            'grands_prix' => 139,
            'first_race' => '2015 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 12,
            'fastest_laps' => 15,
            'highest_race_finish' => '1 (19x)',
            'last_team' => 'Red Bull Toro Rosso Honda (Scuderia Toro Rosso)',
        ],
        [
            'name' => 'Lewis Hamilton',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/lewis-hamilton.html',
            'team' => 'Mercedes-AMG Petronas F1 Team',
            'number' => 44,
            'birthYear' => 1985,
            'nationality' => 'Great Britain',
            'world_championships' => '7 (2008, 2014, 2015, 2017, 2018, 2019, 2020)',
            'wins' => 102,
            'first_win' => 'Formula 1 Grand Prix du Canada 2007',
            'last_win' => 'Formula 1 Ooredoo Qatar Grand Prix 2021',
            'podiums' => 180,
            'points' => 4121.5,
            'grands_prix' => 286,
            'first_race' => '2007 Formula 1 ING Australian Grand Prix',
            'pole_positions' => 102,
            'fastest_laps' => 58,
            'highest_race_finish' => '1 (102x)',
            'last_team' => 'McLaren F1 Team (Vodafone McLaren Mercedes)',
        ],
        [
            'name' => 'Valtteri Bottas',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/valtteri-bottas.html',
            'team' => 'Mercedes-AMG Petronas F1 Team',
            'number' => 77,
            'birthYear' => 1989,
            'nationality' => 'Finland',
            'world_championships' => 0,
            'wins' => 10,
            'first_win' => '2017 Formula 1 VTB Russian Grand Prix',
            'last_win' => 'Formula 1 Rolex Turkish Grand Prix 2021',
            'podiums' => 66,
            'points' => 1715,
            'grands_prix' => 176,
            'first_race' => '2013 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 20,
            'fastest_laps' => 19,
            'highest_race_finish' => '1 (10x)',
            'last_team' => 'Williams Racing (Williams Martini Racing)',
        ],
        [
            'name' => 'Sergio Perez',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/sergio-perez.html',
            'team' => 'Red Bull Racing Honda',
            'number' => 11,
            'birthYear' => 1990,
            'nationality' => 'Mexico',
            'world_championships' => 0,
            'wins' => 2,
            'first_win' => 'Formula 1 Rolex Sakhir Grand Prix 2020',
            'last_win' => 'Formula 1 Azerbaijan Grand Prix 2021',
            'podiums' => 15,
            'points' => 896,
            'grands_prix' => 212,
            'first_race' => '2011 Formula 1 Qantas Australian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 6,
            'highest_race_finish' => '1 (2x)',
            'last_team' => 'BWT Racing Point F1 Team (BWT Racing Point F1 Team)',
        ],
        [
            'name' => 'Lando Norris',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/lando-norris.html',
            'team' => 'McLaren F1 Team',
            'number' => 4,
            'birthYear' => 1999,
            'nationality' => 'Great Britain',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 5,
            'points' => 299,
            'grands_prix' => 58,
            'first_race' => 'Formula 1 Rolex Australian Grand Prix 2019',
            'pole_positions' => 1,
            'fastest_laps' => 3,
            'highest_race_finish' => '2 (1x)',
            'last_team' => 'Carlin (FIA Formula 2 Championship)',
        ],
        [
            'name' => 'Charles Leclerc',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/charles-leclerc.html',
            'team' => 'Scuderia Ferrari Mission Winnow',
            'number' => 16,
            'birthYear' => 1997,
            'nationality' => 'Monaco',
            'world_championships' => 0,
            'wins' => 2,
            'first_win' => 'Formula 1 Johnnie Walker Belgian Grand Prix 2019',
            'last_win' => 'Formula 1 Gran Premio Heineken d Italia 2019',
            'podiums' => 13,
            'points' => 553,
            'grands_prix' => 79,
            'first_race' => 'Formula 1 2018 Rolex Australian Grand Prix',
            'pole_positions' => 9,
            'fastest_laps' => 4,
            'highest_race_finish' => '1 (9x)',
            'last_team' => 'Alfa Romeo Racing Orlen (Alfa Romeo Sauber F1 Team)',
        ],
        [
            'name' => 'Carlos Sainz',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/carlos-sainz.html',
            'team' => 'Scuderia Ferrari Mission Winnow',
            'number' => 55,
            'birthYear' => 1994,
            'nationality' => 'Spain',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 5,
            'points' => 517.5,
            'grands_prix' => 139,
            'first_race' => '2015 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 1,
            'highest_race_finish' => '2 (2x)',
            'last_team' => 'McLaren F1 Team (McLaren F1 Team)',
        ],
        [
            'name' => 'Daniel Ricciardo',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/daniel-ricciardo.html',
            'team' => 'McLaren F1 Team',
            'number' => 3,
            'birthYear' => 1989,
            'nationality' => 'Australia',
            'world_championships' => 0,
            'wins' => 8,
            'first_win' => 'Formula 1 Grand Prix du Canada 2014',
            'last_win' => 'Formula 1 Heineken Gran Premio d Italia 2021',
            'podiums' => 32,
            'points' => 896,
            'grands_prix' => 208,
            'first_race' => '2011 Formula 1 Santander British Grand Prix',
            'pole_positions' => 3,
            'fastest_laps' => 16,
            'highest_race_finish' => '1 (8x)',
            'last_team' => 'Renault F1 Team (Renault DP World F1 Team)',
        ],
        [
            'name' => 'Pierre Gasly',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/pierre-gasly.html',
            'team' => 'Scuderia AlphaTauri Honda',
            'number' => 10,
            'birthYear' => 1996,
            'nationality' => 'France',
            'world_championships' => 0,
            'wins' => 1,
            'first_win' => 'Formula 1 Gran Premio Heineken d Italia 2020',
            'last_win' => 'Formula 1 Gran Premio Heineken d Italia 2020',
            'podiums' => 3,
            'points' => 291,
            'grands_prix' => 84,
            'first_race' => '2017 Formula 1 Petronas Malaysia Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 3,
            'highest_race_finish' => '1 (1x)',
            'last_team' => 'Red Bull Toro Rosso Honda (Red Bull Toro Rosso Honda)',
        ],
        [
            'name' => 'Fernando Alonso',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/fernando-alonso.html',
            'team' => 'Alpine F1 Team',
            'number' => 14,
            'birthYear' => 1981,
            'nationality' => 'Spain',
            'world_championships' => '2 (2005, 2006)',
            'wins' => 32,
            'first_win' => 'Marlboro Magyar Nagydíj 2003',
            'last_win' => 'Formula 1 Gran Premio de España 2013',
            'podiums' => 98,
            'points' => 1976,
            'grands_prix' => 334,
            'first_race' => 'LXVI Qantas Australian Grand Prix 2001',
            'pole_positions' => 22,
            'fastest_laps' => 23,
            'highest_race_finish' => '1 (32x)',
            'last_team' => 'Arrow McLaren SP (IndyCar Series)',
        ],
        [
            'name' => 'Esteban Ocon',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/fernando-alonso.html',
            'team' => 'Alpine F1 Team',
            'number' => 31,
            'birthYear' => 1996,
            'nationality' => 'France',
            'world_championships' => 0,
            'wins' => 1,
            'first_win' => 'Formula 1 Rolex Magyar Nagydíj 2021',
            'last_win' => 'Formula 1 Rolex Magyar Nagydíj 2021',
            'podiums' => 2,
            'points' => 258,
            'grands_prix' => 87,
            'first_race' => '2016 Formula 1 Belgian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '1 (1x)',
            'last_team' => 'Renault F1 Team (Renault DP World F1 Team)',
        ],
        [
            'name' => 'Sebastian Vettel',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/S/SEBVET01_Sebastian_Vettel/sebvet01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/sebastian-vettel.html',
            'team' => 'Aston Martin Cognizant F1 Team',
            'number' => 5,
            'birthYear' => 1987,
            'nationality' => 'Germany',
            'world_championships' => '4 (2010, 2011, 2012, 2013)',
            'wins' => 53,
            'first_win' => 'Formula 1 Gran Premio Santander D Italia 2008',
            'last_win' => 'Formula 1 Singapore Airlines Singapore Grand Prix 2019',
            'podiums' => 122,
            'points' => 3061,
            'grands_prix' => 278,
            'first_race' => '2007 Formula 1 United States Grand Prix',
            'pole_positions' => 57,
            'fastest_laps' => 38,
            'highest_race_finish' => '1 (53x)',
            'last_team' => 'Scuderia Ferrari Mission Winnow (Scuderia Ferrari)',
        ],
        [
            'name' => 'Lance Stroll',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/lance-stroll.html',
            'team' => 'Aston Martin Cognizant F1 Team',
            'number' => 5,
            'birthYear' => 1998,
            'nationality' => 'Canada',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 3,
            'points' => 176,
            'grands_prix' => 98,
            'first_race' => '2017 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 1,
            'fastest_laps' => 0,
            'highest_race_finish' => '3 (3x)',
            'last_team' => 'BWT Racing Point F1 Team (BWT Racing Point F1 Team)',
        ],
        [
            'name' => 'Yuki Tsunoda',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/yuki-tsunoda.html',
            'team' => 'Scuderia AlphaTauri Honda',
            'number' => 22,
            'birthYear' => 2000,
            'nationality' => 'Japan',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 20,
            'grands_prix' => 20,
            'first_race' => 'Formula 1 Gulf Air Bahrain Grand Prix 2021',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '6 (1x)',
            'last_team' => 'Carlin (FIA Formula 2 Championship)',
        ],
        [
            'name' => 'George Russel',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/george-russell.html',
            'team' => 'Williams Racing',
            'number' => 63,
            'birthYear' => 1998,
            'nationality' => 'Great Britain',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 1,
            'points' => 19,
            'grands_prix' => 58,
            'first_race' => 'Formula 1 Rolex Australian Grand Prix 2019',
            'pole_positions' => 0,
            'fastest_laps' => 1,
            'highest_race_finish' => '2 (1x)',
            'last_team' => 'Mercedes-AMG Petronas F1 Team (Mercedes-AMG Petronas F1 Team)',
        ],
        [
            'name' => 'Kimi Räikkönen',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/K/KIMRAI01_Kimi_R%C3%A4ikk%C3%B6nen/kimrai01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/kimi-raikkonen.html',
            'team' => 'Alfa Romeo Racing ORLEN',
            'number' => 7,
            'birthYear' => 1979,
            'nationality' => 'Finland',
            'world_championships' => '1 (2007)',
            'wins' => 21,
            'first_win' => '2003 Petronas Malaysian Grand Prix',
            'last_win' => 'Formula 1 Pirelli 2018 United States Grand Prix',
            'podiums' => 103,
            'points' => 1873,
            'grands_prix' => 350,
            'first_race' => 'LXVI Qantas Australian Grand Prix 2001',
            'pole_positions' => 18,
            'fastest_laps' => 46,
            'highest_race_finish' => '1 (21x)',
            'last_team' => 'Scuderia Ferrari Mission Winnow (Scuderia Ferrari)',
        ],
        [
            'name' => 'Nicholas Latifi',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/N/NICLAF01_Nicholas_Latifi/niclaf01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/nicholas-latifi.html',
            'team' => 'Williams Racing',
            'number' => 6,
            'birthYear' => 1995,
            'nationality' => 'Canada',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 7,
            'grands_prix' => 37,
            'first_race' => 'Formula 1 Rolex Großer Preis von Österreich 2020',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '7 (1x)',
            'last_team' => 'DAMS (FIA Formula 2 Championship)',
        ],
        [
            'name' => 'Antonio Giovinazzi',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/A/ANTGIO01_Antonio_Giovinazzi/antgio01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/antonio-giovinazzi.html',
            'team' => 'Alfa Romeo Racing ORLEN',
            'number' => 9,
            'birthYear' => 1993,
            'nationality' => 'Italy',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 19,
            'grands_prix' => 60,
            'first_race' => '2017 Formula 1 Rolex Australian Grand Prix',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '5 (1x)',
            'last_team' => 'AF Corse (24 Hours of Le Mans – LMGTE Pro)',
        ],
        [
            'name' => 'Mick Schumacher',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/M/MICSCH02_Mick_Schumacher/micsch02.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/mick-schumacher.html',
            'team' => 'Uralkali Haas F1 Team',
            'number' => 47,
            'birthYear' => 1999,
            'nationality' => 'Switzerland',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 0,
            'grands_prix' => 20,
            'first_race' => 'Formula 1 Gulf Air Bahrain Grand Prix 2021',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '12 (1x)',
            'last_team' => 'Prema Racing (Formula 2 Championship)',
        ],
        [
            'name' => 'Robert Kubica',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/R/ROBKUB01_Robert_Kubica/robkub01.png.transform/2col/image.png',
            'website' => 'https://www.formula1.com/en/drivers/robert-kubica.html',
            'team' => 'Alfa Romeo Racing ORLEN',
            'number' => 88,
            'birthYear' => 1984,
            'nationality' => 'Polish',
            'world_championships' => 0,
            'wins' => 1,
            'first_win' => 'Formula 1 Grand Prix du Canada 2008',
            'last_win' => 'Formula 1 Grand Prix du Canada 2008',
            'podiums' => 12,
            'points' => 274,
            'grands_prix' => 99,
            'first_race' => 'Formula 1 Magyar Nagydíj 2006',
            'pole_positions' => 1,
            'fastest_laps' => 1,
            'highest_race_finish' => '1 (1x)',
            'last_team' => 'High Class Racing (FIA World Endurance Championship - LMP2)',
        ],
        [
            'name' => 'Nikita Mazepin',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/N/NIKMAZ01_Nikita_Mazepin/nikmaz01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/nikita-mazepin.html',
            'team' => 'Uralkali Haas F1 Team',
            'number' => 9,
            'birthYear' => 1999,
            'nationality' => 'Russia',
            'world_championships' => 0,
            'wins' => 0,
            'first_win' => '',
            'last_win' => '',
            'podiums' => 0,
            'points' => 0,
            'grands_prix' => 20,
            'first_race' => 'Formula 1 Gulf Air Bahrain Grand Prix 2021',
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'highest_race_finish' => '14 (1x)',
            'last_team' => 'Hitech Grand Prix (FIA Formula 2 Championship)',
        ],
    ];
    $teams = [
        [
            'name' => 'Mercedes-AMG Petronas F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Mercedes/_jcr_content/logo.img.jpg/1582638425211.jpg',
            'website' => 'https://www.formula1.com/en/teams/Mercedes.html',
            'year' => 1954,
            'championships' => '7 (2014, 2015, 2016, 2017, 2018, 2019, 2020)',
            'driversChampionships' => '9 (1954, 1955, 2014, 2015, 2016, 2017, 2018, 2019, 2020)',
            'wins' => 114,
            'podiums' => 261,
            'pole_positions' => 126,
            'fastest_laps' => 84,
            'base' => 'Brackley, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Mercedes-AMG F1 W12 E Performance',
            'racesEntered' => 247,
            'firstEntry' => '1954 French Grand Prix',
            'lastWin' => 'Formula 1 Ooredoo Qatar Grand Prix 2021',
            'firstWin' => '1954 French Grand Prix',
            'highestraceResult' => '1 (114x)',
            'teamPrincipal' => 'Toto Wolff',
            'technical_chief' => 'Mike Elliott',
        ],
        [
            'name' => 'Red Bull Racing Honda',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Red-Bull-Racing/_jcr_content/logo.img.jpg/1610719164360.jpg',
            'website' => 'https://www.formula1.com/en/teams/Red-Bull-Racing.html',
            'year' => 1997,
            'championships' => '4 (2010, 2011, 2012, 2013)',
            'driversChampionships' => '4 (2010, 2011, 2012, 2013)',
            'wins' => 74,
            'podiums' => 204,
            'pole_positions' => 72,
            'fastest_laps' => 75,
            'base' => 'Milton Keynes, United Kingdom',
            'powerUnit' => 'Honda',
            'engine' => 'Honda RA621H',
            'chassis' => 'Red Bull Racing RB16',
            'racesEntered' => 324,
            'firstEntry' => '1997 Australian Grand Prix',
            'lastWin' => 'Formula 1 Gran Premio de la Ciudad de México 2021',
            'firstWin' => '2009 Formula 1 Chinese Grand Prix',
            'highestraceResult' => '1 (74x)',
            'teamPrincipal' => 'Christian Horner',
            'technical_chief' => 'Pierre Waché',
        ],
        [
            'name' => 'Scuderia Ferrari Mission Winnow',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Ferrari/_jcr_content/logo.img.jpg/1521797474166.jpg',
            'website' => 'https://www.formula1.com/en/teams/Ferrari.html',
            'year' => 1950,
            'championships' => '16 (1961, 1964, 1975, 1976, 1977, 1979, 1982, 1983, 1999, 2000, 2001, 2002, 2003, 2004, 2007, 2008)',
            'driversChampionships' => '15 (1952, 1953, 1956, 1958, 1961, 1964, 1975, 1977, 1979, 2000, 2001, 2002, 2003, 2004, 2007)',
            'wins' => 239,
            'podiums' => 772,
            'pole_positions' => 223,
            'fastest_laps' => 253,
            'base' => 'Maranello, Italy',
            'powerUnit' => 'Ferrari',
            'engine' => 'Ferrari 065/6',
            'chassis' => 'Ferrari SF21',
            'racesEntered' => 1030,
            'firstEntry' => 'Prix de Monte-Carlo et XIe Grand Prix Automobile',
            'lastWin' => 'Formula 1 Singapore Airlines Singapore Grand Prix 2019',
            'firstWin' => '1951 British Grand Prix',
            'highestraceResult' => '1 (239x)',
            'teamPrincipal' => 'Mattia Binotto',
            'technical_chief' => 'Enrico Cardile & Enrico Gualtieri',
        ],
        [
            'name' => 'McLaren F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/McLaren/_jcr_content/logo.img.jpg/1515152760829.jpg',
            'website' => 'https://www.formula1.com/en/teams/McLaren.html',
            'year' => 1966,
            'championships' => '8 (1974, 1984, 1985, 1988, 1989, 1990, 1991, 1998)',
            'driversChampionships' => '12 (1974, 1976, 1984, 1985, 1986, 1988, 1989, 1990, 1991, 1998, 1999, 2008)',
            'wins' => 183,
            'podiums' => 493,
            'pole_positions' => 156,
            'fastest_laps' => 160,
            'base' => 'Woking, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes-AMG F1 M12 E Performance',
            'chassis' => 'McLaren MCL35',
            'racesEntered' => 904,
            'firstEntry' => '1966 Monaco Grand Prix',
            'lastWin' => 'Formula 1 Heineken Gran Premio d Italia 2021',
            'firstWin' => '1968 Belgian Grand Prix',
            'highestraceResult' => '1 (183x)',
            'teamPrincipal' => 'Andreas Seidl',
            'technical_chief' => 'James Key',
        ],
        [
            'name' => 'Alpine F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Alpine/_jcr_content/logo.img.jpg/1611246834255.jpg',
            'website' => 'https://www.formula1.com/en/teams/Alpine.html',
            'year' => 1986,
            'championships' => '2 (2005, 2006)',
            'driversChampionships' => '2 (2005, 2006)',
            'wins' => 21,
            'podiums' => 232,
            'pole_positions' => 20,
            'fastest_laps' => 15,
            'base' => 'Enstone, United Kingdom',
            'powerUnit' => 'Renault',
            'engine' => 'Renault E-Tech 20B',
            'chassis' => 'Alpine A521',
            'racesEntered' => 760,
            'firstEntry' => '1986 Brazilian Grand Prix',
            'lastWin' => 'Formula 1 Rolex Magyar Nagydíj 2021',
            'firstWin' => 'XV Fuji Television Japanese Grand Prix 1989',
            'highestraceResult' => '1 (21x)',
            'teamPrincipal' => 'Davide Brivio',
            'technical_chief' => 'Pat Fry & Remi Taffin',
        ],
        [
            'name' => 'Scuderia AlphaTauri Honda',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/AlphaTauri/_jcr_content/logo.img.jpg/1582650557134.jpg',
            'website' => 'https://www.formula1.com/en/teams/AlphaTauri.html',
            'year' => 1985,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 2,
            'podiums' => 5,
            'pole_positions' => 1,
            'fastest_laps' => 2,
            'base' => 'Faenza, Italy',
            'powerUnit' => 'Honda',
            'engine' => 'Honda RA621H',
            'chassis' => 'AlphaTauri AT02',
            'racesEntered' => 651,
            'firstEntry' => 'XIV Grande Prêmio do Brasil 1985',
            'lastWin' => 'Formula 1 Gran Premio Heineken d Italia 2020',
            'firstWin' => 'Formula 1 Gran Premio Santander D Italia 2008',
            'highestraceResult' => '1 (2x)',
            'teamPrincipal' => 'Franz Tost',
            'technical_chief' => 'Jody Egginton',
        ],
        [
            'name' => 'Aston Martin Cognizant F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Aston-Martin/_jcr_content/logo.img.png/1610642928926.png',
            'website' => 'https://www.formula1.com/en/teams/Aston-Martin.html',
            'year' => 2018,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 1,
            'podiums' => 1,
            'pole_positions' => 0,
            'fastest_laps' => 0,
            'base' => 'Silverstone, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Aston Martin AMR21',
            'racesEntered' => 73,
            'firstEntry' => 'Formula 1 2018 Johnnie Walker Belgian Grand Prix',
            'lastWin' => 'Formula 1 Rolex Sakhir Grand Prix 2020',
            'firstWin' => 'Formula 1 Rolex Sakhir Grand Prix 2020',
            'highestraceResult' => '1 (1x)',
            'teamPrincipal' => 'Otmar Szafnauer',
            'technical_chief' => 'Andrew Green',
        ],
        [
            'name' => 'Williams Racing',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Williams/_jcr_content/logo.img.jpg/1590743731407.jpg',
            'website' => 'https://www.formula1.com/en/teams/Williams.html',
            'year' => 1978,
            'championships' => '9 (1980, 1981, 1986, 1987, 1992, 1993, 1994, 1996, 1997)',
            'driversChampionships' => '7 (1980, 1982, 1987, 1992, 1993, 1996, 1997)',
            'wins' => 114,
            'podiums' => 313,
            'pole_positions' => 129,
            'fastest_laps' => 133,
            'base' => 'Grove, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Williams FW43',
            'racesEntered' => 768,
            'firstEntry' => '1978 Argentine Grand Prix',
            'lastWin' => 'Formula 1 Gran Premio de España Santander 2012',
            'firstWin' => 'XXXII Marlboro British Grand Prix 1979',
            'highestraceResult' => '1 (114x)',
            'teamPrincipal' => 'Jost Capito',
            'technical_chief' => 'François-Xavier Demaison',
        ],
        [
            'name' => 'Alfa Romeo Racing ORLEN',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Alfa-Romeo-Racing/_jcr_content/logo.img.jpg/1582650603836.jpg',
            'website' => 'https://www.formula1.com/en/teams/Alfa-Romeo-Racing.html',
            'year' => 1993,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 1,
            'podiums' => 27,
            'pole_positions' => 1,
            'fastest_laps' => 5,
            'base' => 'Hinwil, Switzerland',
            'powerUnit' => 'Ferrari',
            'engine' => 'Ferrari 065/6',
            'chassis' => 'Alfa Romeo Racing C41',
            'racesEntered' => 523,
            'firstEntry' => '1993 South African Grand Prix',
            'lastWin' => 'Formula 1 Grand Prix du Canada 2007',
            'firstWin' => 'Formula 1 Grand Prix du Canada 2007',
            'highestraceResult' => '1 (1x)',
            'teamPrincipal' => 'Frédéric Vasseur',
            'technical_chief' => 'Jan Monchaux',
        ],
        [
            'name' => 'Uralkali Haas F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Haas-F1-Team/_jcr_content/logo.img.jpg/1615481143675.jpg',
            'website' => 'https://www.formula1.com/en/teams/Haas-F1-Team.html',
            'year' => 2016,
            'championships' => 0,
            'driversChampionships' => 0,
            'wins' => 0,
            'podiums' => 0,
            'pole_positions' => 0,
            'fastest_laps' => 2,
            'base' => 'Kannapolis, United States',
            'powerUnit' => 'Ferrari',
            'engine' => 'Ferrari 065/6',
            'chassis' => 'Haas VF-21',
            'racesEntered' => 120,
            'firstEntry' => '2016 Formula 1 Rolex Australian Grand Prix',
            'lastWin' => '',
            'firstWin' => '',
            'highestraceResult' => '4 (1x)',
            'teamPrincipal' => 'Guenther Steiner',
            'technical_chief' => 'Simone Resta',
        ],
    ];
    $champions = [
        [
            'name' => 'Michael Schumacher',
            'image' => '../images/ms.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Michael_Schumacher.html',
            'activeYears' => '1991-2006, 2010-2012',
            'birthYear' => 1969,
            'nationality' => 'Germany',
            'world_championships' => '7 (1994, 1995, 2000, 2001, 2002, 2003, 2004)',
            'wins' => 91,
            'first_win' => '1992 L Grand Prix de Belgique',
            'last_win' => '2006 Formula 1 Sinopec Chinese Grand Prix',
            'podiums' => 155,
            'grands_prix' => 308,
            'first_race' => '1991 XL Grand Prix de Belgique',
            'lastRace' => 'Formula 1 Grande Prêmio Petrobras do Brasil 2012',
            'pole_positions' => 68,
            'fastest_laps' => 77,
            'highest_race_finish' => '1 (91x)',
            'otherTeams' => '<i style="color: #1b6d3e">Team 7UP Jordan</i> (1991), <i style="color: #4a9ecd">Mild Seven Benetton Renault</i> (1991-1995), <i style="color: #ed1c24";>Scuderia Ferrari Marlboro</i> (1996-2006), <i style="color: #009994";>Mercedes AMG Petronas F1 Team</i> (2010-2012)',
        ],
        [
            'name' => 'Lewis Hamilton',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/2col-retina/image.png',
            'website' => 'https://www.lewishamilton.com/',
            'activeYears' => '2007-',
            'birthYear' => 1985,
            'nationality' => 'United Kingdom',
            'world_championships' => '7 (2008, 2014, 2015, 2017, 2018, 2019, 2020)',
            'wins' => 103,
            'first_win' => 'Formula 1 Grand Prix du Canada 2007',
            'last_win' => 'Formula 1 STC Saudi Arabian Grand Prix 2021',
            'podiums' => 182,
            'grands_prix' => 288,
            'first_race' => '2007 Formula 1 ING Australian Grand Prix',
            'lastRace' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'pole_positions' => 103,
            'fastest_laps' => 59,
            'highest_race_finish' => '1 (103x)',
            'otherTeams' => '<i style="color: #ffa112">Vodafone McLaren Mercedes</i> (2007-2012), <i style="color: #009994";>Mercedes-AMG Petronas F1 Team</i> (2013-)',
        ],
        [
            'name' => 'Juan Manuel Fangio',
            'image' => '../images/jmf.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Juan_Manuel_Fangio.html',
            'activeYears' => '1950-1951, 1953-1958',
            'birthYear' => 1911,
            'nationality' => 'Argentina',
            'world_championships' => '5 (1951, 1954, 1955, 1956, 1957)',
            'wins' => 24,
            'first_win' => '1950 Prix de Monte-Carlo et XIe Grand Prix Automobile',
            'last_win' => '1957 XIX Großer Preis von Deutschland',
            'podiums' => 35,
            'grands_prix' => 52,
            'first_race' => '1950 The Royal Automobile Club Grand Prix d\'Europe Incorporating The British Grand Prix',
            'lastRace' => '1958 XLIV Grand Prix de l\'ACF',
            'pole_positions' => 29,
            'fastest_laps' => 23,
            'highest_race_finish' => '1 (103x)',
            'otherTeams' => '<i style="color: #900000">Alfa Romeo SpA</i> (1950-1951), <i style="color: #d40000">Officine Alfieri Maserati</i> (1953-1954, 1957-1958), <i style="color: #009994">Daimler Benz AG</i> (1954-1955), <i style="color: #ed1c24">Scuderia Ferrari</i> (1956), <i style="color: #848b92">Novi Auto Air Conditioner</i> (1958)',
        ],
        [
            'name' => 'Alain Prost',
            'image' => '../images/ap.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Alain_Prost.html',
            'activeYears' => '1980-1991, 1993',
            'birthYear' => 1955,
            'nationality' => 'France',
            'world_championships' => '4 (1985, 1986, 1989, 1993)',
            'wins' => 51,
            'first_win' => '1981 67e Grand Prix de France',
            'last_win' => '1993 Grosser Mobil 1 Preis von Deutschland',
            'podiums' => 106,
            'grands_prix' => 202,
            'first_race' => '1980 XVI Gran Premio de la Republica Argentina',
            'lastRace' => '1993 LVIII Australian Grand Prix',
            'pole_positions' => 33,
            'fastest_laps' => 41,
            'highest_race_finish' => '1 (51x)',
            'otherTeams' => '<i style="color: #ffa112">Honda Marlboro McLaren</i> (1980, 1984-1989), <i style="color: #fff500">Equipe Renault Elf</i> (1981-1983), <i style="color: #ed1c24">Scuderia Ferrari</i> (1990-1991), <i style="color: #005aff">Canon Williams Renault</i> (1993)',
        ],
        [
            'name' => 'Sebastian Vettel',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/S/SEBVET01_Sebastian_Vettel/sebvet01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/sebastian-vettel.html',
            'activeYears' => '2007-',
            'birthYear' => 1987,
            'nationality' => 'Germany',
            'world_championships' => '4 (2010, 2011, 2012, 2013)',
            'wins' => 53,
            'first_win' => 'Formula 1 Gran Premio Santander D\'Italia 2008',
            'last_win' => 'Formula 1 Singapore Airlines Singapore Grand Prix 2019',
            'podiums' => 122,
            'grands_prix' => 280,
            'first_race' => '2007 Formula 1 United States Grand Prix',
            'lastRace' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'pole_positions' => 57,
            'fastest_laps' => 38,
            'highest_race_finish' => '1 (53x)',
            'otherTeams' => '<i style="color: #9b0000">BMW Sauber F1 Team</i> (2006-2007), <i style="color: #000084">Scuderia Toro Rosso</i> (2007-2008), <i style="color: #0600ef">Infiniti Red Bull Racing</i> (2009-2014), <i style="color: #ed1c24">Scuderia Ferrari</i> (2015-2020), <i style="color: #006f62">Aston Martin Cognizant F1 Team</i> (2021-)',
        ],
        [
            'name' => 'Jack Brabham',
            'image' => '../images/jb.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Jack_Brabham.html',
            'activeYears' => '1955-1970',
            'birthYear' => 1926,
            'nationality' => 'Australian',
            'world_championships' => '3 (1959, 1960, 1966)',
            'wins' => 14,
            'first_win' => '1959 XVII Grand Prix Automobile de Monaco',
            'last_win' => '1970 Fourth AA Grand Prix of South Africa',
            'podiums' => 31,
            'grands_prix' => 128,
            'first_race' => '1955 8th RAC British Grand Prix',
            'lastRace' => '1970 Mexican Grand Prix',
            'pole_positions' => 13,
            'fastest_laps' => 12,
            'highest_race_finish' => '1 (14x)',
            'otherTeams' => '<i style="color: #002215">Cooper Car Company</i> (1955, 1957, 1958-1961), <i style="color: #7c7f80">Rob Walker Racing Team</i> (1957), <i style="color: #01639d">Brabham Racing Organisation</i> (1962-1970),',
        ],
        [
            'name' => 'Jackie Stewart',
            'image' => '../images/js.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Jackie_Stewart.html',
            'activeYears' => '1965–1973',
            'birthYear' => 1939,
            'nationality' => 'United Kingdom',
            'world_championships' => '3 (1969, 1971, 1973)',
            'wins' => 27,
            'first_win' => '1965 XXXVI Gran Premio d\'Italia',
            'last_win' => '1973 XXXVIII Großer Preis von Deutschland',
            'podiums' => 43,
            'grands_prix' => 100,
            'first_race' => '1965 11th International RAC Grand Prix of South Africa',
            'lastRace' => '1973 XVI United States Grand Prix',
            'pole_positions' => 17,
            'fastest_laps' => 15,
            'highest_race_finish' => '1 (27x)',
            'otherTeams' => '<i style="color: #182622">Owen Racing Organisation</i> (1965-1967), <i style="color: #1d6fb8">Matra International</i> (1968-1969), <i style="color: #063f87">Elf Team Tyrrell</i> (1970-1973)',
        ],
        [
            'name' => 'Niki Lauda',
            'image' => '../images/nl.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Niki_Lauda.html',
            'activeYears' => '1971–1979, 1982–1985',
            'birthYear' => 1949,
            'nationality' => 'Austria',
            'world_championships' => '3 (1975, 1977, 1984)',
            'wins' => 25,
            'first_win' => '1974 XX Gran Premio de España',
            'last_win' => '1985 XXXIV Grote Prijs van Nederland',
            'podiums' => 54,
            'grands_prix' => 177,
            'first_race' => '1971 IX Großer Preis von Österreich',
            'lastRace' => '1985 L Mitsubishi Australian Grand Prix',
            'pole_positions' => 24,
            'fastest_laps' => 24,
            'highest_race_finish' => '1 (25x)',
            'otherTeams' => '<i style="color: #fef047">STP March Racing Team</i> (1971-1972), <i style="color: #c0c7bf">Marlboro-BRM</i> (1973), <i style="color: #ed1c24">Scuderia Ferrari SpA SEFAC</i> (1974-1977), <i style="color: #282934">Parmalat Racing Team</i> (1978-1979), <i style="color: #ffa112">Marlboro McLaren International</i> (1982-1985)',
        ],
        [
            'name' => 'Nelson Piquet',
            'image' => '../images/np.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Nelson_Piquet.html',
            'activeYears' => '1978–1991',
            'birthYear' => 1952,
            'nationality' => 'Brazil',
            'world_championships' => '3 (1981, 1983, 1987)',
            'wins' => 23,
            'first_win' => '1980 Toyota Grand Prix of Long Beach',
            'last_win' => '1991 Canadian Grand Prix',
            'podiums' => 60,
            'grands_prix' => 207,
            'first_race' => '1978 XL Großer Preis von Deutschland',
            'lastRace' => '1991 Foster’s Australian Grand Prix',
            'pole_positions' => 24,
            'fastest_laps' => 23,
            'highest_race_finish' => '1 (23x)',
            'otherTeams' => '<i style="color: #dd2125">Team Tissot Ensign</i> (1978), <i style="color: #e9ebed">BS Fabrications</i> (1978), <i style="color: #01639d">Motor Racing Developments, Ltd.</i> (1978-1985), <i style="color: #005aff">Canon Williams Team</i> (1986-1987), <i style="color: #ffb800">Camel Team Lotus</i> (1988-1989), <i style="color: #4a9ecd">Camel Benetton Ford</i> (1990-1991)',
        ],
        [
            'name' => 'Ayrton Senna',
            'image' => '../images/as.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Ayrton_Senna.html',
            'activeYears' => '1984-1994',
            'birthYear' => 1960,
            'nationality' => 'Brazil',
            'world_championships' => '3 (1988, 1990, 1991)',
            'wins' => 41,
            'first_win' => '1985 14º Grande Prémio de Portugal',
            'last_win' => '1993 LVIII Australian Grand Prix',
            'podiums' => 80,
            'grands_prix' => 162,
            'first_race' => '1984 XIII Grande Prêmio Brasil de Fórmula 1',
            'lastRace' => '1994 14º Gran Premio di San Marino',
            'pole_positions' => 65,
            'fastest_laps' => 19,
            'highest_race_finish' => '1 (41x)',
            'otherTeams' => '<i style="color: #2c355e">Toleman Group Motorsport</i> (1984), <i style="color: #ffb800">Camel Team Lotus Honda</i> (1985-1987), <i style="color: #ffa112">Marlboro McLaren</i> (1988-1993), <i style="color: #005aff">Rothmans Williams Renault</i> (1994)',
        ],
        [
            'name' => 'Alberto Ascari',
            'image' => '../images/aa.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Alberto_Ascari.html',
            'activeYears' => '1950 – 1955',
            'birthYear' => 1918,
            'nationality' => 'Italy',
            'world_championships' => '2 (1952, 1953)',
            'wins' => 13,
            'first_win' => '1951 XIV Großer Preis von Deutschland',
            'last_win' => '1953 XIII Großer Preis der Schweiz',
            'podiums' => 17,
            'grands_prix' => 33,
            'first_race' => '1950 Prix de Monte-Carlo et XIe Grand Prix Automobile',
            'lastRace' => '1955 XIII Grand Prix Automobile de Monaco',
            'pole_positions' => 14,
            'fastest_laps' => 12,
            'highest_race_finish' => '1 (13x)',
            'otherTeams' => '<i style="color: #ed1c24">Scuderia Ferrari</i> (1950-1954), <i style="color: #d40000">Officine Alfieri Maserati</i> (1954), <i style="color: #fe2932">Scuderia Lancia</i> (1954-1955)',
        ],
        [
            'name' => 'Graham Hill',
            'image' => '../images/gh.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Graham_Hill.html',
            'activeYears' => '1958–1975',
            'birthYear' => 1929,
            'nationality' => 'United Kingdom',
            'world_championships' => '2 (1962, 1968)',
            'wins' => 14,
            'first_win' => '1962 X Grote Prijs van Nederland',
            'last_win' => '1969 XXVII Grand Prix Automobile de Monaco',
            'podiums' => 36,
            'grands_prix' => 179,
            'first_race' => '1958 XVI Grand Prix Automobile',
            'lastRace' => '1975 XXXIII Gran Prix de Monaco',
            'pole_positions' => 13,
            'fastest_laps' => 10,
            'highest_race_finish' => '1 (14x)',
            'otherTeams' => '<i style="color: #ffb800">Team Lotus</i> (1958-1959, 1967-1970), <i style="color: #182622">Owen Racing Organisation</i> (1960-1966), <i style="color: #01639d">Motor Racing Developments Ltd</i> (1971-1972), <i style="color: #d7e3e0">Embassy Racing with Graham Hill</i> (1973-1975)',
        ],
        [
            'name' => 'Jim Clark',
            'image' => '../images/jc.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Jim_Clark.html',
            'activeYears' => '1960–1968',
            'birthYear' => 1936,
            'nationality' => 'United Kingdom',
            'world_championships' => '2 (1963, 1965)',
            'wins' => 25,
            'first_win' => '1962 XXII Grote Prijs van Belgie',
            'last_win' => '1968 2nd AA Grand Prix of South Africa',
            'podiums' => 32,
            'grands_prix' => 73,
            'first_race' => '1960 Dutch Grand Prix',
            'lastRace' => '1968 2nd AA Grand Prix of South Africa',
            'pole_positions' => 33,
            'fastest_laps' => 28,
            'highest_race_finish' => '1 (25x)',
            'otherTeams' => '<i style="color: #ffb800">Team Lotus</i> (1960-1967)',
        ],
        [
            'name' => 'Emerson Fittipaldi',
            'image' => '../images/ef.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Emerson_Fittipaldi.html',
            'activeYears' => '1970–1980',
            'birthYear' => 1946,
            'nationality' => 'Brazil',
            'world_championships' => '2 (1972, 1974)',
            'wins' => 14,
            'first_win' => '1970 XIII United States Grand Prix',
            'last_win' => '1975 John Player Grand Prix',
            'podiums' => 35,
            'grands_prix' => 149,
            'first_race' => '1970 XXIII RAC British Grand Prix',
            'lastRace' => '1980 XXIII Toyota United States Grand Prix',
            'pole_positions' => 6,
            'fastest_laps' => 6,
            'highest_race_finish' => '1 (14x)',
            'otherTeams' => '<i style="color: #ffb800">Team Lotus</i> (1970-1973), <i style="color: #ffa112">Marlboro Team McLaren</i> (1974-1975), <i style="color: #fdf517">Fittipaldi Automotive</i> (1976-1980)',
        ],
        [
            'name' => 'Mika Häkkinen',
            'image' => '../images/mh.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Mika_Hakkinen.html',
            'activeYears' => '1991–2001',
            'birthYear' => 1968,
            'nationality' => 'Finland',
            'world_championships' => '2 (1998, 1999)',
            'wins' => 20,
            'first_win' => '1997 XLII European Grand Prix',
            'last_win' => '2001 SAP United States Grand Prix',
            'podiums' => 51,
            'grands_prix' => 165,
            'first_race' => '1991 XXVIII Iceberg United States Grand Prix',
            'lastRace' => '2001 Fuji Television Japanese Grand Prix',
            'pole_positions' => 26,
            'fastest_laps' => 25,
            'highest_race_finish' => '1 (20x)',
            'otherTeams' => '<i style="color: #ffb800">Team Lotus</i> (1991-1992), <i style="color: #ffa112">West McLaren Mercedes</i> (1993-2001)',
        ],
        [
            'name' => 'Fernando Alonso',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/fernando-alonso.html',
            'activeYears' => '2001, 2003-2018, 2021-',
            'birthYear' => 1981,
            'nationality' => 'Spain',
            'world_championships' => '2 (2005, 2006)',
            'wins' => 32,
            'first_win' => 'Marlboro Magyar Nagydíj 2003',
            'last_win' => 'Formula 1 Gran Premio de España 2013',
            'podiums' => 98,
            'grands_prix' => 336,
            'first_race' => '2001 LXVI Qantas Australian Grand Prix',
            'lastRace' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'pole_positions' => 22,
            'fastest_laps' => 23,
            'highest_race_finish' => '1 (32x)',
            'otherTeams' => '<i style="color: #010203">European Minardi F1</i> (2001), <i style="color: #fff500">Renault F1 Team</i> (2003-2006, 2008-09), <i style="color: #ffa112">McLaren F1 Team</i> (2007, 2015-2018), <i style="color: #0090ff">Alpine F1 Team</i> (2021-)',
        ],
        [
            'name' => 'Giuseppe Farina',
            'image' => '../images/gf.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Nino_Farina.html',
            'activeYears' => '1950–1956',
            'birthYear' => 1906,
            'nationality' => 'Italy',
            'world_championships' => '1 (1950)',
            'wins' => 5,
            'first_win' => '1950 The Royal Automobile Club Grand Prix d\'Europe Incorporating The British Grand Prix',
            'last_win' => '1953 XVI Großer Preis von Deutschland',
            'podiums' => 20,
            'grands_prix' => 36,
            'first_race' => '1950 The Royal Automobile Club Grand Prix d\'Europe Incorporating The British Grand Prix',
            'lastRace' => '1956 40th International 500-Mile Sweepstakes',
            'pole_positions' => 5,
            'fastest_laps' => 5,
            'highest_race_finish' => '1 (5x)',
            'otherTeams' => '<i style="color: #900000">Alfa Romeo SpA</i> (1950-1951), <i style="color: #ed1c24">Scuderia Ferrari</i> (1952-1956)',
        ],
        [
            'name' => 'Mike Hawthorn',
            'image' => '../images/mh2.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Mike_Hawthorn.html',
            'activeYears' => '1952–1958',
            'birthYear' => 1929,
            'nationality' => 'United Kingdom',
            'world_championships' => '1 (1958)',
            'wins' => 3,
            'first_win' => '1953 XL Grand Prix de l\'ACF',
            'last_win' => '1958 XLIV Grand Prix de l\'ACF',
            'podiums' => 18,
            'grands_prix' => 47,
            'first_race' => '1952 XIV GROTE PRIJS VAN BELGIE',
            'lastRace' => '1958 VII Grand Prix International Automobile du Maroc',
            'pole_positions' => 4,
            'fastest_laps' => 6,
            'highest_race_finish' => '1 (3x)',
            'otherTeams' => '<i style="color: #002215">Leslie D. Hawthorn</i> (1952), <i style="color: #ed1c24">Scuderia Ferrari</i> (1953-1955, 1957-1958), <i style="color: #00503f">Vandervell Products</i> (1955-1956), <i style="color: #182622">Owen Racing Organisation</i> (1956), <i style="color: #d40000">Officine Alfieri Maserati</i> (1956)',
        ],
        [
            'name' => 'Phil Hill',
            'image' => '../images/ph.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Phil_Hill.html',
            'activeYears' => '1958–1964, 1966',
            'birthYear' => 1927,
            'nationality' => 'United States',
            'world_championships' => '1 (1961)',
            'wins' => 3,
            'first_win' => '1960 XXXI Gran Premio d\'Italia',
            'last_win' => '1961 XXXII Gran Premio d\'Italia',
            'podiums' => 16,
            'grands_prix' => 52,
            'first_race' => '1958 XLIV Grand Prix de l\'ACF',
            'lastRace' => '1966 XXXVII Gran Premio d\'Italia',
            'pole_positions' => 6,
            'fastest_laps' => 6,
            'highest_race_finish' => '1 (3x)',
            'otherTeams' => '<i style="color: #d40000">Jo Bonnier</i> (1958), <i style="color: #ed1c24">Scuderia Ferrari</i> (1958-1960, 1961-1962), <i style="color: #002215">Cooper Car Company</i> (1960, 1964), <i style="color: #949896">Porsche System Engineering</i> (1962), <i style="color: #de7a8c">Automobili Turismo e Sport</i> (1963), <i style="color: #ffb800">Ecurie Filipinetti</i> (1963, 1966), <i style="color: #ffa112">Phil Hill</i> (1966), <i style="color: #24263e">Anglo American Racers</i> (1966)',
        ],
        [
            'name' => 'John Surtees',
            'image' => '../images/js2.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/John_Surtees.html',
            'activeYears' => '1960–1972',
            'birthYear' => 1934,
            'nationality' => 'United Kingdom',
            'world_championships' => '1 (1964)',
            'wins' => 6,
            'first_win' => '1963 XXV Grosser Preis von Deutschland',
            'last_win' => '1967 XXXVIII Gran Premio d\'Italia',
            'podiums' => 24,
            'grands_prix' => 113,
            'first_race' => '1960 XVIII Grand Prix Automobile de Monaco',
            'lastRace' => '1972 43o Gran Premio d\'Italia',
            'pole_positions' => 8,
            'fastest_laps' => 11,
            'highest_race_finish' => '1 (6x)',
            'otherTeams' => '<i style="color: #ffb800">Team Lotus</i> (1960), <i style="color: #002215">Bowmaker-Yeoman Racing Team</i> (1961-1962), <i style="color: #ed1c24">Scuderia Ferrari SpA SEFAC</i> (1963-1966), <i style="color: #002215">Cooper Car Company</i> (1966), <i style="color: #ece7e3">Honda Racing</i> (1967-1968), <i style="color: #182622">Owen Racing Organisation</i> (1969), <i style="color: #182550">Team Surtees</i> (1970-1972)',
        ],
        [
            'name' => 'Denny Hulme',
            'image' => '../images/dh.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Denny_Hulme.html',
            'activeYears' => '1965–1974',
            'birthYear' => 1936,
            'nationality' => 'Australian',
            'world_championships' => '1 (1967)',
            'wins' => 8,
            'first_win' => '1967 XXV Grand Prix Automobile de Monaco',
            'last_win' => '1974 XI Gran Premio de la Republica Argentina',
            'podiums' => 33,
            'grands_prix' => 112,
            'first_race' => '1965 XXIII Grand Prix de Monaco',
            'lastRace' => '1974 XVII United States Grand Prix',
            'pole_positions' => 1,
            'fastest_laps' => 9,
            'highest_race_finish' => '1 (8x)',
            'otherTeams' => '<i style="#c0c7bf">Brabham Racing Organisation</i> (1965-1967), <i style="color: #ffa112">Marlboro Team Texaco</i> (1968-1974)',
        ],
        [
            'name' => 'Jochen Rindt',
            'image' => '../images/jr.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Jochen_Rindt.html',
            'activeYears' => '1964–1970',
            'birthYear' => 1942,
            'nationality' => 'Austria',
            'world_championships' => '1 (1970)',
            'wins' => 6,
            'first_win' => '1969 XII United States Grand Prix',
            'last_win' => '1970 German Grand Prix',
            'podiums' => 13,
            'grands_prix' => 62,
            'first_race' => '1964 II Großer Preis von Österreich',
            'lastRace' => '1970 XLI Gran Premio d\'Italia',
            'pole_positions' => 10,
            'fastest_laps' => 3,
            'highest_race_finish' => '1 (6x)',
            'otherTeams' => '<i style="color: #c0c7bf">Rob Walker Racing Team</i> (1964), <i style="color: #002215">Cooper Car Company</i> (1965-1967), <i style="color: #c0c7bf">Brabham Racing Organisation</i> (1968), <i style="color: #ffb800">Gold Leaf Team Lotus</i> (1969-1970)',
        ],
        [
            'name' => 'James Hunt',
            'image' => '../images/jh.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/James_Hunt.html',
            'activeYears' => '1973–1979',
            'birthYear' => 1947,
            'nationality' => 'United Kingdom',
            'world_championships' => '1 (1976)',
            'wins' => 10,
            'first_win' => '1975 XXII Grand Prix Zandvoort',
            'last_win' => '1977 XII Japanese Grand Prix',
            'podiums' => 23,
            'grands_prix' => 93,
            'first_race' => '1973 XXXI Grand Prix de Monaco',
            'lastRace' => '1979 Monaco Grand Prix',
            'pole_positions' => 14,
            'fastest_laps' => 8,
            'highest_race_finish' => '1 (10x)',
            'otherTeams' => '<i style="color: #fef047">Hesketh Racing</i> (1973-1975), <i style="color: #ffa112">Marlboro Team McLaren</i> (1976-1978), <i style="color: #e7c4ab">Olympus Cameras Wolf Racing</i> (1979)',
        ],
        [
            'name' => 'Mario Andretti',
            'image' => '../images/ma.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Mario_Andretti.html',
            'activeYears' => '1968–1972, 1974–1982',
            'birthYear' => 1940,
            'nationality' => 'United States',
            'world_championships' => '1 (1978)',
            'wins' => 12,
            'first_win' => '1971 Fifth AA Grand Prix of South Africa',
            'last_win' => '1978 Dutch Grand Prix',
            'podiums' => 19,
            'grands_prix' => 131,
            'first_race' => '1968 XI United States Grand Prix',
            'lastRace' => '1982 2nd Caesars Palace Grand Prix',
            'pole_positions' => 18,
            'fastest_laps' => 10,
            'highest_race_finish' => '1 (12x)',
            'otherTeams' => '<i style="color: #ffb800">Martini Racing Team Lotus</i> (1968-1969, 1976,  1977-1980), <i style="color: #fef047">STP Corporation</i> (1970), <i style="color: #ed1c24">Scuderia Ferrari SpA SEFAC</i> (1971-1972, 1982), <i style="color: #c4002e">Vel\'s Parnelli Jones Racing</i> (1974-1975, 1976), <i style="color: #900000">Marlboro Team Alfa Romeo</i> (1981), <i style="color: #005aff">TAG Williams Team</i> (1982)',
        ],
        [
            'name' => 'Jody Scheckter',
            'image' => '../images/js3.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Jody_Scheckter.html',
            'activeYears' => '1972 – 1980',
            'birthYear' => 1950,
            'nationality' => 'South Africa',
            'world_championships' => '1 (1979)',
            'wins' => 10,
            'first_win' => '1974 Swedish Grand Prix',
            'last_win' => '1979 50o Gran Premio d\'Italia',
            'podiums' => 33,
            'grands_prix' => 113,
            'first_race' => '1972 XV United States Grand Prix',
            'lastRace' => '1980 XXIII Toyota United States Grand Prix',
            'pole_positions' => 3,
            'fastest_laps' => 3,
            'highest_race_finish' => '1 (10x)',
            'otherTeams' => '<i style="color: #ffa112">Yardley Team McLaren</i> (1972-1973), <i style="color: #063f87">Elf Team Tyrrell</i> (1974-1976), <i style="color: #e7c4ab">Walter Wolf Racing</i> (1977-1978), <i style="color: #ed1c24">Scuderia Ferrari</i> (1979-1980)',
        ],
        [
            'name' => 'Alan Jones',
            'image' => '../images/aj.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Alan_Jones.html',
            'activeYears' => '1975–1981, 1983, 1985–1986',
            'birthYear' => 1946,
            'nationality' => 'Australian',
            'world_championships' => '1 (1980)',
            'wins' => 12,
            'first_win' => '1977 XV Gröbl Möbel Großer Preis von Österreich',
            'last_win' => '1981 1st Caesars Palace Grand Prix',
            'podiums' => 24,
            'grands_prix' => 117,
            'first_race' => '1975 XXI Gran Premio de España',
            'lastRace' => '1986 LI Foster\'s Australian Grand Prix',
            'pole_positions' => 6,
            'fastest_laps' => 13,
            'highest_race_finish' => '1 (12x)',
            'otherTeams' => '<i style="color: #d7e3e0">Custom Made Harry Stiller Racing</i> (1975), <i style="color: #d7e3e0">Embassy Racing with Graham Hill</i> (1975), <i style="color: #3e6fc5">Shadow Racing Team</i> (1976-1977), <i style="color: #005aff">TAG Williams Team</i> (1978-1981), <i style="color: #ba4f63">Arrows Racing Team</i> (1983), <i style="color: #e05c45">Team Haas (USA) Ltd</i> (1985-1986)',
        ],
        [
            'name' => 'Keke Rosberg',
            'image' => '../images/kr.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Keke_Rosberg.html',
            'activeYears' => '1978–1986',
            'birthYear' => 1948,
            'nationality' => 'Finland',
            'world_championships' => '1 (1982)',
            'wins' => 5,
            'first_win' => '1982 Swiss Grand Prix',
            'last_win' => '1985 L Mitsubishi Australian Grand Prix',
            'podiums' => 17,
            'grands_prix' => 128,
            'first_race' => '1978 XXIV Citizen and Asseng Grand Prix of South Africa',
            'lastRace' => '1986 LI Foster\'s Australian Grand Prix',
            'pole_positions' => 5,
            'fastest_laps' => 3,
            'highest_race_finish' => '1 (5x)',
            'otherTeams' => '<i style="color: #57513e">Theodore Racing Hong Kong</i> (1978), <i style ="color: #e4a50c">ATS Racing Team</i> (1978), <i style="color: #e7c4ab">Olympus Cameras Wolf Racing</i> (1979), <i style="color: #fdf517">Fittipaldi Automotive</i> (1980-1981), <i style="color: #005aff">Canon Williams Team</i> (1982-1985), <i style="color: #ffa112">Marlboro McLaren International</i> (1986)',
        ],
        [
            'name' => 'Nigel Mansell',
            'image' => '../images/nm.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Nigel_Mansell.html',
            'activeYears' => '1980–1992, 1994–1995',
            'birthYear' => 1953,
            'nationality' => 'United Kingdom',
            'world_championships' => '1 (1992)',
            'wins' => 31,
            'first_win' => '1985 Shell Oils Grand Prix of Europe',
            'last_win' => '1994 LIX Adelaide Australian Grand Prix',
            'podiums' => 59,
            'grands_prix' => 191,
            'first_race' => '1980 XVIII Großer Preis von Osterreich',
            'lastRace' => '1995 XXXVII Gran Premio Marlboro de España',
            'pole_positions' => 32,
            'fastest_laps' => 30,
            'highest_race_finish' => '1 (31x)',
            'otherTeams' => '<i style="color: #ffb800">John Player Special Team Lotus</i> (1980-1984), <i style="color: #005aff">Rothmans Williams Renault</i> (1985-1988, 1991-1992, 1994), <i style="color: #ed1c24">Scuderia Ferrari</i> (1989-1990),  <i style="color: #ffa112">Marlboro McLaren Mercedes</i> (1995)',
        ],
        [
            'name' => 'Damon Hill',
            'image' => '../images/dh2.jpg',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Damon_Hill.html',
            'activeYears' => '1992–1999',
            'birthYear' => 1960,
            'nationality' => 'United Kingdom',
            'world_championships' => '1 (1996)',
            'wins' => 22,
            'first_win' => '1993 IX Marlboro Magyar Nagydíj',
            'last_win' => '1998 LVI Foster\'s Belgian Grand Prix',
            'podiums' => 42,
            'grands_prix' => 122,
            'first_race' => '1992 Gran Premio Tío Pepe de España',
            'lastRace' => '1999 XXV Fuji Television Japanese Grand Prix',
            'pole_positions' => 20,
            'fastest_laps' => 19,
            'highest_race_finish' => '1 (22x)',
            'otherTeams' => '<i style="color: #01639d">Motor Racing Developments</i> (1992), <i style="color: #005aff">Rothmans Williams Renault</i> (1993-1996), <i style="color: #ba4f63">Danka Arrows Yamaha</i> (1997), <i style="color: #1b6d3e">B&H Jordan</i> (1998-1999)',
        ],
        [
            'name' => 'Jacques Villeneuve',
            'image' => '../images/jv.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Jacques_Villeneuve.html',
            'activeYears' => '1996–2006',
            'birthYear' => 1971,
            'nationality' => 'Canada',
            'world_championships' => '1 (1997)',
            'wins' => 11,
            'first_win' => '1996 XL Grand Prix of Europe',
            'last_win' => 'Grosser Preis von Luxemburg 1997',
            'podiums' => 23,
            'grands_prix' => 165,
            'first_race' => '1996 Australian Grand Prix',
            'lastRace' => 'Formula 1 Grosser Mobil 1 Preis von Deutschland 2006',
            'pole_positions' => 13,
            'fastest_laps' => 9,
            'highest_race_finish' => '1 (11x)',
            'otherTeams' => '<i style="color: #005aff">Winfield Williams</i> (1996-1998), <i style="color: #ece7e3">Lucky Strike BAR Honda</i> (1999-2003), <i style="color: #fff500">Mild Seven Renault F1 Team</i> (2004), <i style="color: #9b0000">BMW Sauber F1 Team</i> (2005-2006)',
        ],
        [
            'name' => 'Kimi Räikkönen',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/K/KIMRAI01_Kimi_R%C3%A4ikk%C3%B6nen/kimrai01.png.transform/2col-retina/image.png',
            'website' => 'https://www.kimiraikkonen.com/',
            'activeYears' => '2001–2009, 2012–2021',
            'birthYear' => 1979,
            'nationality' => 'Finland',
            'world_championships' => '1 (2007)',
            'wins' => 21,
            'first_win' => '2003 Petronas Malaysian Grand Prix',
            'last_win' => 'Formula 1 Pirelli 2018 United States Grand Prix',
            'podiums' => 103,
            'grands_prix' => 353,
            'first_race' => '2001 LXVI Qantas Australian Grand Prix',
            'lastRace' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'pole_positions' => 18,
            'fastest_laps' => 46,
            'highest_race_finish' => '1 (21x)',
            'otherTeams' => '<i style="color: #9b0000">Red Bull Sauber Petronas</i> (2001), <i style="color: #ffa112">Team McLaren Mercedes</i> (2002-2006), <i style="color: #ed1c24">Scuderia Ferrari</i> (2007-2009, 2014-2018), <i style="color: #ffb800">Lotus F1 Team</i> (2012-2013), <i style="color: #900000">Alfa Romeo Racing Orlen</i> (2019-2021)',
        ],
        [
            'name' => 'Jenson Button',
            'image' => '../images/jb2.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Jenson_Button.html',
            'activeYears' => '2000–2017',
            'birthYear' => 1980,
            'nationality' => 'United Kingdom',
            'world_championships' => '1 (2009)',
            'wins' => 15,
            'first_win' => 'Formula 1 Magyar Nagydíj 2006',
            'last_win' => 'Formula 1 Grande Prêmio Petrobras do Brasil 2012',
            'podiums' => 50,
            'grands_prix' => 309,
            'first_race' => '2000 Qantas Australian Grand Prix',
            'lastRace' => '2017 75e Formula 1 Grand Prix de Monaco',
            'pole_positions' => 8,
            'fastest_laps' => 8,
            'highest_race_finish' => '1 (15x)',
            'otherTeams' => '<i style="color: #005aff">BMW Williams F1 Team</i> (2000), <i style="color: #fff500">Mild Seven Renault F1 Team</i> (2001-2002), <i style="color: #ece7e3">Honda Racing F1 Team</i> (2003-2008), <i style="color: #f2f279">Brawn GP F1 Team</i> (2009), <i style="color: #ffa112">McLaren Honda</i> (2010-2017)',
        ],
        [
            'name' => 'Nico Rosberg',
            'image' => '../images/nr.png',
            'website' => 'https://www.formula1.com/en/drivers/hall-of-fame/Nico_Rosberg.html',
            'activeYears' => '2006–2016',
            'birthYear' => 1985,
            'nationality' => 'Germany',
            'world_championships' => '1 (2016)',
            'wins' => 23,
            'first_win' => '2012 Formula 1 UBS Chinese Grand Prix',
            'last_win' => '2016 Formula 1 Emirates Japanese Grand Prix',
            'podiums' => 57,
            'grands_prix' => 206,
            'first_race' => '2006 Formula 1 Gulf Air Bahrain Grand Prix',
            'lastRace' => '2016 Formula 1 Etihad Airways Abu Dhabi Grand Prix',
            'pole_positions' => 30,
            'fastest_laps' => 20,
            'highest_race_finish' => '1 (23x)',
            'otherTeams' => '<i style="color: #005aff">AT&T Williams</i> (2006-2009), <i style="color: #009994">Mercedes AMG Petronas F1 Team</i> (2010-2016)',
        ],
        [
            'name' => 'Max Verstappen',
            'image' => 'https://www.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col-retina/image.png',
            'website' => 'https://www.formula1.com/en/drivers/max-verstappen.html',
            'activeYears' => '2015-',
            'birthYear' => 1997,
            'nationality' => 'Netherlands',
            'world_championships' => '1 (2021)',
            'wins' => 20,
            'first_win' => 'Formula 1 Gran Premio de España Pirelli 2016',
            'last_win' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'podiums' => 60,
            'grands_prix' => 141,
            'first_race' => '2015 Formula 1 Rolex Australian Grand Prix',
            'lastRace' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'pole_positions' => 13,
            'fastest_laps' => 16,
            'highest_race_finish' => '1 (20x)',
            'otherTeams' => '<i style="color: #000084">Scuderia Toro Rosso</i> (2015-2016), <i style="color: #0600ef">Red Bull Racing Honda</i> (2016-)',
        ],
    ];
    $constructors = [
        [
            'name' => 'Scuderia Ferrari Mission Winnow',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Ferrari/_jcr_content/logo.img.jpg/1521797474166.jpg',
            'website' => 'https://www.ferrari.com/en-BR/formula1',
            'year' => 1950,
            'championships' => '16 (1961, 1964, 1975, 1976, 1977, 1979, 1982, 1983, 1999, 2000, 2001, 2002, 2003, 2004, 2007, 2008)',
            'driversChampionships' => '15 (1952, 1953, 1956, 1958, 1961, 1964, 1975, 1977, 1979, 2000, 2001, 2002, 2003, 2004, 2007)',
            'driversChampions' => 'Alberto Ascari (1952, 1953), Juan Manuel Fangio (1956), Mike Hawthorn (1958), Phil Hill (1961), John Surtees (1964), Niki Lauda (1975, 1977), Jody Scheckter (1979), Michael Schumacher (2000, 2001, 2002, 2003, 2004), Kimi Räikkönen (2007)',
            'wins' => 239,
            'podiums' => 773,
            'pole_positions' => 223,
            'fastest_laps' => 253,
            'base' => 'Maranello, Italy',
            'powerUnit' => 'Ferrari',
            'engine' => 'Ferrari 065/6',
            'chassis' => 'Ferrari SF21',
            'racesEntered' => 1032,
            'firstEntry' => '1950 Prix de Monte-Carlo et XIe Grand Prix Automobile',
            'lastEntry' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'lastWin' => 'Formula 1 Singapore Airlines Singapore Grand Prix 2019',
            'firstWin' => '1951 IV RAC British Grand Prix',
            'highestraceResult' => '1 (239x)',
            'teamPrincipal' => 'Mattia Binotto',
            'technical_chief' => 'Enrico Cardile & Enrico Gualtieri',
            'lastNames' => 'Scuderia Ferrari (1950-1960, 1976, 1990-1996, 2011-2020), Scuderia Ferrari SpA SEFAC(1961-1975, 1977-1989), Scuderia Ferrari Marlboro (1997-2010)',
            'seasons' => '1950-',
        ],
        [
            'name' => 'Williams Racing',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Williams/_jcr_content/logo.img.jpg/1590743731407.jpg',
            'website' => 'https://www.williamsf1.com/',
            'year' => 1978,
            'championships' => '9 (1980, 1981, 1986, 1987, 1992, 1993, 1994, 1996, 1997)',
            'driversChampionships' => '7 (1980, 1982, 1987, 1992, 1993, 1996, 1997)',
            'driversChampions' => 'Alan Jones (1980), Keke Rosberg (1982), Nelson Piquet (1987), Nigel Mansell (1992), Alain Prost (1993), Damon Hill (1996), Jacques Villeneuve (1997)',
            'wins' => 114,
            'podiums' => 313,
            'pole_positions' => 129,
            'fastest_laps' => 133,
            'base' => 'Grove, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Williams FW43',
            'racesEntered' => 770,
            'firstEntry' => '1978 Argentine Grand Prix',
            'lastEntry' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'lastWin' => 'Formula 1 Gran Premio de España Santander 2012',
            'firstWin' => '1977 French Grand Prix',
            'highestraceResult' => '1 (114x)',
            'teamPrincipal' => 'Jost Capito',
            'technical_chief' => 'François-Xavier Demaison',
            'lastNames' => 'Williams Grand Prix Engineering (1978, 1984), Albilad-Saudia Racing Team (1979-1981), TAG Williams Team (1982-1983), Canon Williams Honda Team (1985-1987), Canon Williams Team (1988-1992), Canon Williams (1993), Rothmans Williams Renault (1994-1997), Winfield Williams (1998-1999), BMW WilliamsF1 Team (2000-2005), Williams F1 Team (2006, 2012-2013), AT&T Williams (2007-2011), Williams Martini Racing (2014-2018), ROKiT Williams Racing (2019)',
            'seasons' => '1978-',
        ],
        [
            'name' => 'McLaren F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/McLaren/_jcr_content/logo.img.jpg/1515152760829.jpg',
            'website' => '	www.mclaren.com/racing',
            'year' => 1966,
            'championships' => '8 (1974, 1984, 1985, 1988, 1989, 1990, 1991, 1998)',
            'driversChampionships' => '12 (1974, 1976, 1984, 1985, 1986, 1988, 1989, 1990, 1991, 1998, 1999, 2008)',
            'driversChampions' => 'Emerson Fittipaldi (1974), James Hunt (1976), Niki Lauda (1984), Alain Prost (1985, 1986, 1989), Ayrton Senna (1988, 1990, 1991), Mika Häkkinen (1998, 1999), Lewis Hamilton (2008)',
            'wins' => 183,
            'podiums' => 493,
            'pole_positions' => 156,
            'fastest_laps' => 160,
            'base' => 'Woking, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes-AMG F1 M12 E Performance',
            'chassis' => 'McLaren MCL35',
            'racesEntered' => 906,
            'firstEntry' => '1966 XXIV Grand Prix Automobile de Monaco',
            'lastEntry' => 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021',
            'lastWin' => 'Formula 1 Heineken Gran Premio d\'Italia 2021',
            'firstWin' => '1968 XXVIII Grand Prix de Belgique',
            'highestraceResult' => '1 (183x)',
            'teamPrincipal' => 'Andreas Seidl',
            'technical_chief' => 'James Key',
            'lastNames' => 'Bruce McLaren Motor Racing (1966-1971), Yardley Team McLaren (1972-1974), Marlboro Team Texaco (1974), Marlboro Team McLaren (1975-1979, 1980), Löwenbräu Team McLaren (1979), Marlboro McLaren International (1981-1987), Honda Marlboro McLaren (1988-1992), Marlboro McLaren (1993), Marlboro McLaren Peugeot (1994), Marlboro McLaren Mercedes (1995-1996), West McLaren Mercedes (1997-2004), Team McLaren Mercedes (2005-2006), Vodafone McLaren Mercedes (2007-2013), McLaren Mercedes (2014), McLaren Honda (2015), McLaren Honda Formula 1 Team (2016-2017)',
            'seasons' => '1966-',
        ],
        [
            'name' => 'Mercedes-AMG Petronas F1 Team',
            'image' => 'https://www.formula1.com/content/fom-website/en/teams/Mercedes/_jcr_content/logo.img.jpg/1582638425211.jpg',
            'website' => 'https://www.mercedesamgf1.com/en/',
            'year' => 1970,
            'championships' => '8 (2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021)',
            'driversChampionships' => '9 (1954, 1955, 2014, 2015, 2016, 2017, 2018, 2019, 2020)',
            'driversChampions' => 'Juan Manuel Fangio (1954-1955), Lewis Hamilton (2014, 2015, 2016, 2017, 2018, 2019, 2020), Nico Rosberg (2016)',
            'wins' => 115,
            'podiums' => 261,
            'pole_positions' => 127,
            'fastest_laps' => 85,
            'base' => 'Brackley, United Kingdom',
            'powerUnit' => 'Mercedes',
            'engine' => 'Mercedes M12 E Performance',
            'chassis' => 'Mercedes-AMG F1 W12 E Performance',
            'racesEntered' => 247,
            'firstEntry' => '1954 XLI Grand Prix de l\'ACF',
            'lastEntry' => '',
            'lastWin' => 'Formula 1 Ooredoo Qatar Grand Prix 2021',
            'firstWin' => '1954 French Grand Prix',
            'highestraceResult' => '1 (115x)',
            'teamPrincipal' => 'Toto Wolff',
            'technical_chief' => 'Mike Elliott',
            'lastNames' => '',
            'seasons' => '',
        ],
    ];
    $teamsWithWinsThisSeason = [
        '',
        '',
        '',
        ''
    ];
    $races = [
        ['location' => 'Bahrein', 'date' => '1647745200', 'dateTime' => '2022-03-20 00:00:00', 'circuit' => 'Bahrain International Circuit', 'grand_prix' => 'Gulf Air Bahrain Grand Prix'],
        ['location' => 'Arábia Saudita', 'date' => '1648350000', 'dateTime' => '2022-03-27 00:00:00', 'circuit' => 'Jeddah Corniche Circuit', 'grand_prix' => 'STC Saudi Arabian Grand Prix'],
        ['location' => 'Austrália', 'date' => '1649559600', 'dateTime' => '2022-04-10 00:00:00', 'circuit' => 'Albert Park Circuit', 'grand_prix' => 'Rolex Australian Grand Prix'],
        ['location' => 'Itália', 'date' => '1650769200', 'dateTime' => '2022-04-24 00:00:00', 'circuit' => 'Imola Circuit', 'grand_prix' => 'Pirelli Gran Premio del Made in Italy e dell\'Emilia Romagna'],
        ['location' => 'Estados Unidos', 'date' => '1651978800', 'dateTime' => '2022-05-08 00:00:00', 'circuit' => 'Miami International Autodrome', 'grand_prix' => 'Miami Grand Prix'],
        ['location' => 'Espanha', 'date' => '1653188400', 'dateTime' => '2022-05-22 00:00:00', 'circuit' => 'Circuit de Barcelona-Catalunya', 'grand_prix' => 'Aramco Gran Premio de España'],
        ['location' => 'Mônaco', 'date' => '1653793200', 'dateTime' => '2022-05-29 00:00:00', 'circuit' => 'Circuit de Monaco', 'grand_prix' => 'Grand Prix de Monaco'],
        ['location' => 'Azerbaijão', 'date' => '1655002800', 'dateTime' => '2022-06-12 00:00:00', 'circuit' => 'Baku City Circuit', 'grand_prix' => 'Azerbaijan Grand Prix'],
        ['location' => 'Canadá', 'date' => '1655607600', 'dateTime' => '2022-06-19 00:00:00', 'circuit' => 'Circuit Gilles Villeneuve', 'grand_prix' => 'Pirelli Grand Prix du Canada'],
        ['location' => 'Reino Unido', 'date' => '1656817200', 'dateTime' => '2022-07-03 00:00:00', 'circuit' => 'Silverstone Circuit', 'grand_prix' => 'Pirelli British Grand Prix'],
        ['location' => 'Áustria', 'date' => '1657422000', 'dateTime' => '2022-07-10 00:00:00', 'circuit' => 'Red Bull Ring', 'grand_prix' => 'BWT Grosser Preis von Österreich'],
        ['location' => 'França', 'date' => '1658631600', 'dateTime' => '2022-07-24 00:00:00', 'circuit' => 'Circuit Paul Ricard', 'grand_prix' => 'Emirates Grand Prix de France'],
        ['location' => 'Hungria', 'date' => '1659236400', 'dateTime' => '2022-07-31 00:00:00', 'circuit' => 'Hungaroring', 'grand_prix' => 'Rolex Magyar Nagydíj'],
        ['location' => 'Bélgica', 'date' => '1661655600', 'dateTime' => '2022-08-28 00:00:00', 'circuit' => 'Circuit de Spa-Francorchamps', 'grand_prix' => 'Rolex Belgian Grand Prix'],
        ['location' => 'Holanda', 'date' => '1662260400', 'dateTime' => '2022-09-04 00:00:00', 'circuit' => 'Circuit Zandvoort', 'grand_prix' => 'Heineken Dutch Grand Prix'],
        ['location' => 'Itália', 'date' => '1662865200', 'dateTime' => '2022-09-11 00:00:00', 'circuit' => 'Monza Circuit', 'grand_prix' => 'Heineken Gran Premio d\'Italia'],
        ['location' => 'Russia', 'date' => '1664074800', 'dateTime' => '2022-09-25 00:00:00', 'circuit' => 'Sochi Autodrom', 'grand_prix' => 'VTB Russian Grand Prix'],
        ['location' => 'Singapura', 'date' => '1664679600', 'dateTime' => '2022-10-02 00:00:00', 'circuit' => 'Marina Bay Street Circuit', 'grand_prix' => 'Singapore Airlines Singapore Grand Prix'],
        ['location' => 'Japão', 'date' => '1665284400', 'dateTime' => '2022-10-09 00:00:00', 'circuit' => 'Suzuka International Racing Course', 'grand_prix' => 'Japanese Grand Prix'],
        ['location' => 'Estados Unidos', 'date' => '1666494000', 'dateTime' => '2022-10-23 00:00:00', 'circuit' => 'Circuit of the Americas', 'grand_prix' => 'Aramco United States Grand Prix'],
        ['location' => 'México', 'date' => '1667098800', 'dateTime' => '2022-10-30 00:00:00', 'circuit' => 'Autódromo Hermanos Rodríguez', 'grand_prix' => 'Gran Premio de la Ciudad de México'],
        ['location' => 'Brasil', 'date' => '1668308400', 'dateTime' => '2022-11-13 00:00:00', 'circuit' => 'Autódromo de Interlagos', 'grand_prix' => 'Heineken Grande Prêmio de São Paulo'],
        ['location' => 'Emirados Árabes Unidos', 'date' => '1668913200', 'dateTime' => '2022-11-20 00:00:00', 'circuit' => 'Yas Marina Circuit', 'grand_prix' => 'Etihad Airways Abu Dhabi Grand Prix'],
    ];